### ISSUE TITLE
Removing SignAssembly attribute from csproj

### ISSUE THREAD

**Issue by PugachA** [mattosaurus/PgpCore#102]
Why did you remove the assembly sign in this commit https://github.com/mattosaurus/PgpCore/commit/1e690fa9270e5d143abe83752ccaea929e673b32?

Only `2.2.0` version has strong name. Is this an accident or intentional action?

**Comment by mattosaurus** [comment]
I'm not sure why this was removed, it wasn't intentional, I'll re-enable strong naming from your PR.
