### ISSUE TITLE
DecryptStreamAndVerifyAsync method returning "File was not signed."

### ISSUE THREAD

**Issue by kyrancook** [mattosaurus/PgpCore#107]
Hi there,

I am trying use the DecryptStreamAndVerifyAsync method, however it returns the "File was not signed." error message.

I have proven that original file was signed by the expected sender as I was able to verify the signature using gpg4win tool.

I would appreciate if I could get some advice on how to debug this issue.

Thanks

**Comment by mattosaurus** [comment]
Hi,

I'm assuming the file was also encrypted as well as signed? If it's just a signed file you'll need to use VerifyStreamAsync instead.

If you can replicate this issue and provide me with a test file, keys and password then I'll have a look into it and see if I can figure out what's going on.

Thanks

**Comment by kyrancook** [comment]
Hi,

This issue has been resolved by updating the pgpcore package to the latest
version. Happy to close this out.

Thanks
