### ISSUE TITLE
Verifying a detached signature

### ISSUE THREAD

**Issue by mprigge** [mattosaurus/PgpCore#124]
Looking at the documentation, I gather it's not currently possible to verify a detached signature using this library (`gpg --verify file.txt.sig file.txt`). I'm working with a scenario where I need to sign and verify large (>1GB) binary files, so the opaque signed encoding isn't really acceptable due to the storage overhead it introduces.  

Is that something that's envisioned as a feature that might be introduced?  Or is it currently possible somehow?

**Comment by mprigge** [comment]
I dug further into the BouncyCastle library and determined how to do it directly there. Still might be a good addition for this library (which certainly boils a lot of the complexity out), but I found what I needed.

**Comment by mattosaurus** [comment]
Excellent, glad you found what you needed. If you feel like it feel free to sumbit a PR adding this functionality, or if not I'll try and add it at somepoint as I agree that it would be auseful addition.
