### ISSUE TITLE
Decrypt a file using just a passphrase?

### ISSUE THREAD

**Issue by mrthornhill** [mattosaurus/PgpCore#126]
I have a file provided to me that was apparently pgp encrypted with just a passphrase.
I am able to decrypt it at the command line via:
`gpg -d FileName.csv.pgp`
(I'm prompted for the passphrase, enter it, and it's decrypted)

I would like to use PgpCore to do this programmatically within our application, however I cannot find a means to Decrypt that does not require a private key (which I do not have).

Is this possible with this library?
Thanks!

**Comment by mattosaurus** [comment]
Hi, currently decryption just via passphrase isn't supported though this is something I may consider adding in future.
