### ISSUE TITLE
Empty outputStream when using DecryptStreamAsync

### ISSUE THREAD

**Issue by reko91** [mattosaurus/PgpCore#132]
After running the following code, the outputStream is always empty:

`

        public static async Task<MemoryStream> Decrypt(Stream privateKeyStream, byte[] inputData)
        {
            // Load keys
            EncryptionKeys encryptionKeys = new EncryptionKeys(privateKeyStream, "password");
            PGP pgp = new PGP(encryptionKeys);
            MemoryStream outputMemoryStream;
            using (MemoryStream inputMemoryStream = new MemoryStream(inputData))
            {
                using (outputMemoryStream = new MemoryStream())
                {
                    try
                    {
                        await pgp.DecryptStreamAsync(inputMemoryStream, outputMemoryStream);
                        var x = "";
                    }
                    catch(Exception exc)
                    {
                        var checkException = exc;
                    }                    
                }
            }
            return outputMemoryStream;
        }`

Any ideas what this could be?

**Comment by reko91** [comment]
Even when using the code from the [docs ](https://github.com/mattosaurus/PgpCore#decrypt)I get an empty file:

`
// Load keys
EncryptionKeys encryptionKeys;
using (Stream privateKeyStream = new FileStream(@"C:\TEMP\Keys\private.asc", FileMode.Open))
	encryptionKeys = new EncryptionKeys(privateKeyStream, "password");

PGP pgp = new PGP(encryptionKeys);

// Reference input/output files
using (FileStream inputFileStream = new FileStream(@"C:\TEMP\Content\encryptedContent.pgp", FileMode.Open))
using (Stream outputFileStream = File.Create(@"C:\TEMP\Content\decrypted.txt"))
	// Decrypt
	await pgp.DecryptStreamAsync(inputFileStream, outputFileStream);

`

Must be something to do with the way I encrypted it. I encrypted it using Kleopatra.

**Comment by mattosaurus** [comment]
Hi, sorry I'm away at the moment so won't be able to look at this until next week. If you're able to share the encrypted file and key (or test versions of them) then that will make things easier.

**Comment by reko91** [comment]
> Hi, sorry I'm away at the moment so won't be able to look at this until next week. If you're able to share the encrypted file and key (or test versions of them) then that will make things easier.

I can send you the file but I'm also getting an empty file when encrypting using [generated keys](https://github.com/mattosaurus/PgpCore#generatekey) from your examples. The outputFileStream has data in, but it doesn't look to write it to file.

**Comment by reko91** [comment]
Looks like the keys I was using weren't correct. When I generated the keys using your [generation code](https://github.com/mattosaurus/PgpCore#generatekey) it works. I generated my keypair using Kleopatra, any idea why this would be different?
