### ISSUE TITLE
"Can't find encryption key in key ring."

### ISSUE THREAD

**Issue by deibertf** [mattosaurus/PgpCore#133]
```cs
Utilities.ReadPublicKey(pkFileName) //throws "Can't find encryption key in key ring."
```

```cs
Utilities.ReadPublicKey(pkFileStream) //does work without any problem
```

I am using version `5.3.1`.

To my understanding ReadPublicKey(string file) should just be a wrapper and open a stream itself.

**Comment by deibertf** [comment]
Wow this makes perfect sense. For some reason I expected it to be the path to the file.
I am pretty sure this worked before.

**Comment by mattosaurus** [comment]
Commented these specific methods in v5.3.2
