### ISSUE TITLE
PgpSignatureList type implementation is missing in Verify/VerifyAsync

### ISSUE THREAD

**Issue by pawelt4b** [mattosaurus/PgpCore#134]
PgpSignatureList (not PgpOnePassSignatureList) type implementation is missing in methods Verify/VerifyAsync.

The exception is thrown:

Org.BouncyCastle.Bcpg.OpenPgp.PgpException
Message is not a encrypted and signed file or simple signed file.
Boolean Verify(System.IO.Stream)
   at PgpCore.PGP.Verify(Stream inputStream)
   at PgpCore.PGP.VerifyFile(String inputFilePath)

**Comment by mattosaurus** [comment]
Just published v5.3.2
