### ISSUE TITLE
Problems decrypting and verifying files with the old signature type (PGP 2.x)

### ISSUE THREAD

**Issue by alegri240** [mattosaurus/PgpCore#138]
Version: Pgpcore 5.3.2, .Net 6.0

I'm trying to decrypt and verify a file I received from a vendor. I get the error "An unhandled exception of type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpException' occurred in PgpCore.dll: 'File was not signed.". When I do the same thing through gnupg it works, but I get the information: signature of the old (PGP 2.x) type.

**Comment by alegri240** [comment]
Its seems to be a RSA 2048 key...

**Comment by mattosaurus** [comment]
Cool, well if you can provide me with a keypair and file that replicate the problem I'll take a look.
