### ISSUE TITLE
Is it possible to use use private key for encryption and public key for decryption?

### ISSUE THREAD

**Issue by reko91** [mattosaurus/PgpCore#149]
It seems as though the encryption method expects the PgpPublicKeyRing. Is it possible to use the private key for encryption then use the public key to decrypt?

**Comment by mattosaurus** [comment]
Hi, the encryption methods can take key references firectly as inputs.

https://github.com/mattosaurus/PgpCore#encrypt

The public key is required for encryption and the private key for decryption.

**Comment by RodneyRichardson** [comment]
@reko91 What are you trying to achieve? If it's to prove that a file came from a particular person, you may be looking at the Sign functionality instead. This takes a private key, and creates a signature that can verify the contents of the file using the public key.
