### ISSUE TITLE
Multiparty encryption

### ISSUE THREAD

**Issue by jlaprade-git** [mattosaurus/PgpCore#150]
I don't see any documented functionality to allow for multi party encryption in Pgpcore. 
Is it possible to have the ability to encrypt to multiple public keys? If not, is this on the roadmap?

**Comment by mattosaurus** [comment]
Hi, multipart decryption is supported but multipart encryption is not supported yet. This would be a good feature to add though there's nothing quite as formal as a roadmap so I'll get around to it when I get a chance.

**Comment by mattosaurus** [comment]
Actually, I think multipart encryption is available although I haven't used it for a while. I'll see if I can add some tests to confirm it still works as expected.

**Comment by mattosaurus** [comment]
So this is available and does seem to work, see the following test for an example.

https://github.com/mattosaurus/PgpCore/blob/22b90f0a45258f1232e03b9f095841dcd75afd15/PgpCore.Tests/UnitTests/UnitTestsAsync.cs#L1100-L1138
