### ISSUE TITLE
Encrypted data seems to be corrupted.

### ISSUE THREAD

**Issue by briansg8888** [mattosaurus/PgpCore#154]
Hi, I use pgp core on my C# azure function as below in azure blob trigger. However the encrypted file seems to be corrupted. Hope you can advise on it. Thanks. Is there any restriction on the gpg key that can be used for encyrption?

Code:            EncryptionKeys encryptionkey = new EncryptionKeys(publicKey);
                    PGP pgp = new PGP(encryptionkey);
                    pgp.EncryptStreamAsync(inputBlob, outputBlob);

Output:
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.8.9.0

hQEMA1Z0B/HJnlz4AQf/ew5jTabthj8qn+a+8emDZ5fWaitm7Dvmw9r4pjrh5NCD
xcL+IfT1u86l+ixifCF8l2EDTnPMIVfUWInX3Gb4IBx4zr+/PTW/2rXUWLnTHkPf
1wFRWzx2ufEgO6ZJAY39+N3Fr+VjVKJfG9IUmlRWDBfmQdOALb7Ae+Mvuc037/zt
I36CTLRDCLeIGW86nqhRlrSZJHA9DeS9GeHbibDCfcYUCihvFi5QM5dKBsANnuBh
vRkAlT2EqMVAZn0VN7VItjdJ0ubff/cSqyvP/slq1JR4E19gp/XK3J/mev8z4VeY
yckrbIYbAcFPRgPpzKz3/jZqihtTBYuLbJci4128

Note: missing end pgp, seems not properly formatted.

**Comment by mattosaurus** [comment]
Hi, you're not awaiting EncryptStreamAsync so the stream gets cut off when your function completes.

**Comment by briansg8888** [comment]
Thanks . I tried the encryptstream method instead of encrypt streamasync and it seems to be working . Able to enlighten me what’s the difference or any site can tell me more about it . Thanks for advice

**Comment by mattosaurus** [comment]
Async is used to run tasks in parallel whereas sync will run it within the current thread.

So for example if your function works like this.

1. Encrypts file
2. Checks to see if file with same name already exists
3. If file doesn't then save, else append version number.

Then running the tasks in sync means they'll take place one after the other whereas running steps 1 and 2 async would allow them to take place in parallel. You can start a task and then check if it's completed later.

```
var encryptTask = pgp.EncryptFileAsync("myFileName");
var fileExistsTask = CheckFileExists("myFileName2);

await encryptTask;
await fileExistsTask;

// Save file
```

Even if you don't care about running things in parallel it's still generally better to use async methods where possible as the fact that they run in different threads means they have more resources available to them.

There's a lot of good documentation around this but I'd recommend you check out the Microsoft docs initially which will give you a better explanation than I managed :)

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

**Comment by briansg8888** [comment]
Thanks!
