### ISSUE TITLE
Public Key With Subkey Throwing 'Can't find encryption key in key ring.'

### ISSUE THREAD

**Issue by vthokie93** [mattosaurus/PgpCore#157]
I'll apologize in advance if this is a lack of understanding on my part. I have receive a public key that has subkeys Certify, Sign (Primary) and Encrypt. 

<img width="815" alt="Subkeys" src="https://user-images.githubusercontent.com/9801363/166508258-2fce4d35-80f8-49f9-9ec8-ddda283860d7.png">

When I try to encrypt using this key the following exception is thrown:

'System.ArgumentException' in System.Private.CoreLib.dll: 'Can't find encryption key in key ring.'

**Comment by vthokie93** [comment]
I discovered it is an issue with the way I am handling the file.

**Comment by mattosaurus** [comment]
👍
