### ISSUE TITLE
Decrypt stream output is disposed object?

### ISSUE THREAD

**Issue by premsonbaby** [mattosaurus/PgpCore#167]
The output of the following async method is disposed stream.
 
public Task<Stream> DecryptStreamAsync(Stream inputStream, Stream outputStream);

There is no point of this outputStream if its disposed , it is creating file on disk, but it will be helpful to use the outputStream if its not empty for further stream related actions after decryption. Rather than reading the decrypted file again from disk.

thanks.

**Comment by mattosaurus** [comment]
This outputs a stream to wherever you want it.

https://github.com/mattosaurus/PgpCore#decryptstreamasync

The example writes to a FileStream but you could output to a MemoryStream or similar if you wanted.

**Comment by premsonbaby** [comment]
Thank you.

I understand that, but what I said is, the following function signature tells me that it return a stream, but that stream is disposed. 

**public Task<Stream> DecryptStreamAsync(Stream inputStream, Stream outputStream);**

as i said before its definitely creating file on disk. but if you try to use the return value its disposed object.


**Following is my example code  :**

//as per the examples 
public async Task<Stream> DecryptStreamAsync(Stream privateKeyStream, string password, Stream inputFileStream, string outputFile)
        {
            var encryptionKeys = new EncryptionKeys(privateKeyStream, password);
            PGP pgp = new PGP(encryptionKeys);
            await using Stream outputFileStream = File.Create(outputFile);
            return await pgp.DecryptStreamAsync(inputFileStream, outputFileStream);
        }

//My code
var tst_stream = await CryptographyService.DecryptStreamAsync(decryptionKeyStream, decryptionPGPKeyPassword.Value, inputBlob, uniqueTempFileName); //My code

//the tst_stream is a disposed object.
//so i have to do the following 

var fileToUpload = new FileStream(uniqueTempFileName, FileMode.Open); 

So when i try to open the decrypted file as per the above code some times i am getting an error that another process is using the file, this is not happening all the time but but when you process multiple files in a short period of time.

hope this is clear.

thanks.
