### ISSUE TITLE
Got an exception of: Cannot access a closed Stream.

### ISSUE THREAD

**Issue by jing-ge-star** [mattosaurus/PgpCore#169]
Pgp version: 5.7.0
Framework: .net core

Code example:

public static string Decrypt(List<byte> bytes, List<byte> keyBytes, string password)
{
    using var key = new MemoryStream(keyBytes.ToArray());
    using var pgp = new PGP(new EncryptionKeys(key, password));
    using var input = new MemoryStream(bytes.ToArray());
    using var output = new MemoryStream();
    var a = pgp.DecryptStream(input, output);
    var content = StringHelper.GetString(output);
    return content;
}

![image](https://user-images.githubusercontent.com/71301497/183087515-2540c346-4369-4c59-8c6c-219747f38d6c.png)

**Comment by mattosaurus** [comment]
Sorry for the late reply.

If you want a string containing the decrypted content it would be easier to use the relevant method.

https://github.com/mattosaurus/PgpCore#decryptarmoredstringasync

**Comment by mattosaurus** [comment]
This is hopefully fixed in v5.9.0 with #174
