### ISSUE TITLE
error when decrypting.

### ISSUE THREAD

**Issue by ganga1984** [mattosaurus/PgpCore#17]
Below is my code, we genreated the pgp key pair using Go anywhere software, the code is reading the public key of the sender but giving error on reading my private key.The error is "Org.BouncyCastle.Bcpg.OpenPgp.PgpPublicKeyRing found where PgpSecretKeyRing expected". Please help its urgent.

            PGPDecrypt test = new PGPDecrypt(@"d:\PGP_Keys\TestKeys\INT328.txt.pgp",
                                                @"d:/PGP_Keys/TestKey/My secret key.asc",
                                                "XXXX",
                                                path1,
                                                @"d:/PGP_Keys/TestKey/Sender public key.asc", true);
            FileStream fs = File.Open(@"d:\PGP_Keys\TestKeys\INT328.txt.pgp", FileMode.Open);
                test.decrypt(fs, path1);
                fs.Close();
-----------------------------------

public class PgpEncryptionKeys
    {
        public PgpPublicKey PublicKey { get; private set; }
        public PgpPrivateKey PrivateKey { get; private set; }
        public PgpSecretKey SecretKey { get; private set; }

        /// <summary>
        /// Initializes a new instance of the EncryptionKeys class.
        /// Two keys are required to encrypt and sign data. Your private key and the recipients public key.
        /// The data is encrypted with the recipients public key and signed with your private key.
        /// </summary>

        /// <param name="publicKeyPath">The key used to encrypt the data</param>
        /// <param name="privateKeyPath">The key used to sign the data.</param>
        /// <param name="passPhrase">The (your) password required to access the private key</param>
        /// <exception cref="ArgumentException">Public key not found. Private key not found. Missing password</exception>

        public PgpEncryptionKeys(string publicKeyPath, string privateKeyPath, string passPhrase,bool toEncrypt)
        {

            if (!File.Exists(publicKeyPath))
                throw new ArgumentException("Public key file not found", "publicKeyPath");

            if (!File.Exists(privateKeyPath))
                throw new ArgumentException("Private key file not found", "privateKeyPath");

            if (String.IsNullOrEmpty(passPhrase))
                throw new ArgumentException("passPhrase is null or empty.", "passPhrase");

            PublicKey = ReadPublicKey(publicKeyPath);
            SecretKey = ReadSecretKey(privateKeyPath, toEncrypt);
            PrivateKey = ReadPrivateKey(passPhrase);

        }

        #region Secret Key
        /// <summary>
        /// Return the last key we can use to decrypt.
        /// Note: A file can contain multiple keys (stored in "key rings")
        /// </summary>
        private PgpSecretKey GetLastSecretKey(PgpSecretKeyRingBundle secretKeyRingBundle)
        {
            return (from PgpSecretKeyRing kRing in secretKeyRingBundle.GetKeyRings()
                    select kRing.GetSecretKeys().Cast<PgpSecretKey>()
                                                    .LastOrDefault(k => k.IsSigningKey))
                                                    .LastOrDefault(key => key != null);
        }
        private PgpSecretKey ReadSecretKey(string privateKeyPath, bool toEncrypt)
        {
            using (Stream keyIn = File.OpenRead(privateKeyPath))
            using (Stream inputStream = PgpUtilities.GetDecoderStream(keyIn))
            {
                PgpSecretKeyRingBundle secretKeyRingBundle = new PgpSecretKeyRingBundle(inputStream);
                PgpSecretKey foundKey = toEncrypt ? GetFirstSecretKey(secretKeyRingBundle): GetLastSecretKey(secretKeyRingBundle);
                // PgpSecretKey foundKey = GetFirstSecretKey(secretKeyRingBundle);
                if (foundKey != null)
                    return foundKey;
            }
            throw new ArgumentException("Can't find signing key in key ring.");
        }

        /// <summary>
        /// Return the first key we can use to encrypt.
        /// Note: A file can contain multiple keys (stored in "key rings")
        /// </summary>
        private PgpSecretKey GetFirstSecretKey(PgpSecretKeyRingBundle secretKeyRingBundle)
        {
            foreach (PgpSecretKeyRing kRing in secretKeyRingBundle.GetKeyRings())
            {
                PgpSecretKey key = kRing.GetSecretKeys().Cast<PgpSecretKey>().Where(k => k.IsSigningKey).FirstOrDefault();

                if (key != null)
                    return key;
            }
            return null;
        }

        #endregion

        #region Public Key
        private PgpPublicKey ReadPublicKey(string publicKeyPath)
        {
            using (Stream keyIn = File.OpenRead(publicKeyPath))
            using (Stream inputStream = PgpUtilities.GetDecoderStream(keyIn))
            {
                PgpPublicKeyRingBundle publicKeyRingBundle = new PgpPublicKeyRingBundle(inputStream);
                PgpPublicKey foundKey = GetFirstPublicKey(publicKeyRingBundle);
                if (foundKey != null)
                    return foundKey;
            }
            throw new ArgumentException("No encryption key found in public key ring.");
        }

        private PgpPublicKey GetFirstPublicKey(PgpPublicKeyRingBundle publicKeyRingBundle)
        {

            foreach (PgpPublicKeyRing kRing in publicKeyRingBundle.GetKeyRings())
            {
                PgpPublicKey key = kRing.GetPublicKeys()
                    .Cast<PgpPublicKey>()
                    .Where(k => k.IsEncryptionKey)
                    .FirstOrDefault();

                if (key != null)
                    return key;
            }
            return null;
        }

        #endregion

        #region Private Key

        private PgpPrivateKey ReadPrivateKey(string passPhrase)
        {
            PgpPrivateKey privateKey = SecretKey.ExtractPrivateKey(passPhrase.ToCharArray());
            if (privateKey != null)
                return privateKey;

            throw new ArgumentException("No private key found in secret key.");

        }

        #endregion
    }

**Comment by mattosaurus** [comment]
Hi, are you actually using the PgpCore package?  PGPDecrypt isn't an object in it.

**Comment by mattosaurus** [comment]
@Absamis, please open a new issue and include your code along with the version of PgpCore being used.
