### ISSUE TITLE
Azure Blob Storage Example bad link

### ISSUE THREAD

**Issue by slava888v** [mattosaurus/PgpCore#170]
The Azure example (Blob Storage) link seems to be not working. 
Any chance you could repoint it? 
Thank you.

**Comment by mattosaurus** [comment]
Hmm, the link works for me. Here's the example project though.

https://github.com/mattosaurus/PgpEncrypt

**Comment by slava888v** [comment]
Interesting. 

Here is what I’m getting.

**Comment by mattosaurus** [comment]
Turns out I'm an idiot and the repository was private!

Have made it public now.

**Comment by slava888v** [comment]
Thanks mattosaurus!
