### ISSUE TITLE
Error dotnetCore 3.1 Linux: ObjectDisposedException in DecryptFile(string, string)

### ISSUE THREAD

**Issue by k5123** [mattosaurus/PgpCore#175]
Hi,

The latest builds of my software on Github appear to reference a newer version of PgpCore than 5.6.0, which appears to have broken:

> 2022-09-13 15:58:41,817 [PROC: 23801  ] [ERROR] Failed to decrypt file_A.zip.pgp: ObjectDisposedException: Cannot access a closed stream.
> 2022-09-13 15:58:41,836 [PROC: 23801  ] [DEBUG]    at System.IO.BufferedStream.EnsureNotClosed()
>    at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
>    at Org.BouncyCastle.Bcpg.BcpgInputStream.Read(Byte[] buffer, Int32 offset, Int32 count) in /_/crypto/src/bcpg/BcpgInputStream.cs:line 69
>    at Org.BouncyCastle.Crypto.IO.CipherStream.ReadAndProcessBlock() in /_/crypto/src/crypto/io/CipherStream.cs:line 113
>    at Org.BouncyCastle.Crypto.IO.CipherStream.FillInBuf() in /_/crypto/src/crypto/io/CipherStream.cs:line 96
>    at Org.BouncyCastle.Crypto.IO.CipherStream.Read(Byte[] buffer, Int32 offset, Int32 count) in /_/crypto/src/crypto/io/CipherStream.cs:line 72
>    at Org.BouncyCastle.Bcpg.BcpgInputStream.Read(Byte[] buffer, Int32 offset, Int32 count) in /_/crypto/src/bcpg/BcpgInputStream.cs:line 69
>    at Org.BouncyCastle.Bcpg.BcpgInputStream.PartialInputStream.Read(Byte[] buffer, Int32 offset, Int32 count) in /_/crypto/src/bcpg/BcpgInputStream.cs:line 332
>    at System.IO.BufferedStream.ReadByteSlow()
>    at System.IO.BufferedStream.ReadByte()
>    at Org.BouncyCastle.Bcpg.BcpgInputStream.ReadByte() in /_/crypto/src/bcpg/BcpgInputStream.cs:line 43
>    at Org.BouncyCastle.Bcpg.LiteralDataPacket..ctor(BcpgInputStream bcpgIn) in /_/crypto/src/bcpg/LiteralDataPacket.cs:line 20
>    at Org.BouncyCastle.Bcpg.BcpgInputStream.ReadPacket() in /_/crypto/src/bcpg/BcpgInputStream.cs:line 232
>    at Org.BouncyCastle.Bcpg.OpenPgp.PgpLiteralData..ctor(BcpgInputStream bcpgInput) in /_/crypto/src/openpgp/PgpLiteralData.cs:line 24
>    at Org.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.NextPgpObject() in /_/crypto/src/openpgp/PgpObjectFactory.cs:line 89
>    at PgpCore.PGP.Decrypt(Stream inputStream, Stream outputStream)
>    at PgpCore.PGP.DecryptFile(String inputFilePath, String outputFilePath)

**Comment by mattosaurus** [comment]
Which version of PgpCore are you using?

This was an issue with 5.7 and 5.8 but should be fixed in 5.8.1

**Comment by k5123** [comment]
Not entirely sure what version Github's build loads, trying to see that in the logs.

**Comment by mattosaurus** [comment]
It should work in 5.6 and earlier unless you have v1.9 of bouncy castle installed as that's where this issue was introduced.

**Comment by k5123** [comment]
Thank you. I upgraded all to 5.8.1 and can confirm this fixed. Closing :)
