### ISSUE TITLE
Possibility to encrypt and sign with multiple public keys

### ISSUE THREAD

**Issue by KubasGC** [mattosaurus/PgpCore#18]
Hi.

I want to add a possibility to encrypt file with multiple public keys and sign it with one private key. Is it possible with PgpCore?

**Comment by mattosaurus** [comment]
It's not possible at the moment, though given that there's already a method to encrypt using multiple public keys it should be pretty simple to update the EncryptAndSign method for multiple public key use. I'll have a look at this later.

**Comment by mattosaurus** [comment]
Turns out this is more complicated than I thought. I've pushed some changes to the development branch but haven't had a chance to check they actually work yet, will have a look at this tomorrow.

https://github.com/mattosaurus/PgpCore/tree/development

**Comment by mattosaurus** [comment]
I've pushed out version 1.4 which allows you to encrypt and sign using multiple keys, everything seems fine to me but let me know if you have any issues.
