### ISSUE TITLE
Issue while decrypting

### ISSUE THREAD

**Issue by paritoshnagar2016** [mattosaurus/PgpCore#180]
While Decrypting the file, getting below error. I can see the error is happening under Decrypt(Stream inputStream, Stream outputStream)
method under below block of code

				if (message is PgpCompressedData pgpCompressedData)
				{
					Stream compDataIn = pgpCompressedData.GetDataStream().DisposeWith(disposables);
					PgpObjectFactory objectFactory = new PgpObjectFactory(compDataIn);
					**message = objectFactory.NextPgpObject();** //This is returning PgpSignatureList & that is not available in 
below code so it goes into else condition and try to unbox message that is 
PgpSignatureList into PgpLiteralData and throwing exception.
 Do you know reason why? but if I do another message = objectFactory.NextPgpObject(); 
that returns PgpLiteralData  & that wrks fine. Looks like there is 
some issue can you please help to see if it can be fixed

					if (message is PgpOnePassSignatureList)
					{
						message = objectFactory.NextPgpObject();
						PgpLiteralData literalData = (PgpLiteralData)message;
						Stream unc = literalData.GetInputStream();
						Streams.PipeAll(unc, outputStream);
					}
					else
					{
						PgpLiteralData literalData = (PgpLiteralData)message;
						Stream unc = literalData.GetInputStream();
						Streams.PipeAll(unc, outputStream);
					}
				}
System.InvalidCastException: Unable to cast object of type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpSignatureList' to type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpLiteralData'.
   at PgpCore.PGP.Decrypt(Stream inputStream, Stream outputStream)
   at PgpCore.PGP.DecryptStream(Stream inputStream, Stream outputStream)
   at PgpCore.PGP.DecryptFile(FileInfo inputFile, FileInfo outputFile)

**Comment by mattosaurus** [comment]
Hi, I'm not sure what may be causing this, possibly an issue with how your file was created.

Are you able to provide a sample encrypted file with keys and password and I'll try and investigate locally?

**Comment by kauheanoita** [comment]
I had the same issue using PgpCore so I couldnt use it with the files I have. This is what I did (note the PgpSignatureList):

```
                using (Stream clear = pbe.GetDataStream(privKey))
                {
                    PgpObjectFactory plainFact = new PgpObjectFactory(clear);
                    PgpObject message = plainFact.NextPgpObject();

                    if (message is PgpCompressedData)
                    {
                        PgpCompressedData cData = (PgpCompressedData)message;
                        Stream compDataIn = cData.GetDataStream();
                        PgpObjectFactory o = new PgpObjectFactory(compDataIn);

                        while ((message = o.NextPgpObject()) != null)
                        {
                            if (message is PgpOnePassSignatureList || message is PgpSignatureList)
                            {
                                continue;
                            }
                            else if(message is PgpLiteralData)
                            {
                                PgpLiteralData Ld = (PgpLiteralData)message;
                                Stream unc = Ld.GetInputStream();
                                Streams.PipeAll(unc, outputStream);

                                break;
                            }
                        }
                    }
                }

```

**Comment by mattosaurus** [comment]
@kauheanoita, thanks for posting that solution.

I've made a small tweak in this branch.

https://github.com/mattosaurus/PgpCore/tree/bug/decrypt-PgpSignatureList

Are to able to let me know if that fixes the issue please.

**Comment by kauheanoita** [comment]
With that fix DecryptStream works with my file. DecryptStreamAndVerify has a similar problem but if I change pgp.cs "private void DecryptAndVerify(Stream inputStream, Stream outputStream)" around line 5381 like this it will also work

```
				if (message is PgpCompressedData cData)
				{
					Stream compDataIn = cData.GetDataStream().DisposeWith(disposables);
					PgpObjectFactory objectFactory = new PgpObjectFactory(compDataIn);
					message = objectFactory.NextPgpObject();

					long? keyIdToVerify = null;

					if (message is PgpSignatureList pgpSignatureList)
					{
						keyIdToVerify = pgpSignatureList[0].KeyId;
					}
					else if (message is PgpOnePassSignatureList pgpOnePassSignatureList)
					{
						PgpOnePassSignature pgpOnePassSignature = pgpOnePassSignatureList[0];
						keyIdToVerify = pgpOnePassSignature.KeyId;
					}

					if(keyIdToVerify.HasValue)
					{ 
						var verified = Utilities.FindPublicKey(keyIdToVerify.Value, EncryptionKeys.VerificationKeys,
							out PgpPublicKey _);
						if (verified == false)
							throw new PgpException("Failed to verify file.");

						message = objectFactory.NextPgpObject();
						var literalData = (PgpLiteralData)message;
						Stream unc = literalData.GetInputStream();
						Streams.PipeAll(unc, outputStream);
					}
					else
					{
						throw new PgpException("File was not signed.");
					}
				}
```

Unfortunately I can't share my keys or the encrypted file.

**Comment by mattosaurus** [comment]
I've just published v5.9 to hopefully resolve this.

**Comment by DanWillman** [comment]
Hey there, I'm also running into this exception and am on v5.9. This issue seemed the most related, but @mattosaurus if you want me to make a new issue for this, just let me know.

Unfortunately I'm not able to share the keys I used to test this, but I did generate a fresh set of pairs (public and private, encryption and signature) internally to validate this

Stack trace:
```
Unable to cast object of type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpLiteralData' to type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpEncryptedDataList'.
   at PgpCore.PGP.DecryptAndVerify(Stream inputStream, Stream outputStream)
   at PgpCore.PGP.DecryptStreamAndVerify(Stream inputStream, Stream outputStream)
```

Here's the code from an XUnit test I used to verify this:

```
[Fact]
public void Test()
{
    using var inStream = new MemoryStream();
    using var clearStream = new MemoryStream();
    using var writer = new StreamWriter(inStream);
    var clearText = "someTest";
    var signatureKey = "path/to/signature";
    var publicSignatureKey = "path/to/PublicSignatureKey";
    var signatureKeyPassword = "password";
    var publicKey = "path/to/publicEncryptionKey"
    var privateKey = "path/to/privateEncryptionKey";
    var privateKeyPassword = "password";

    writer.Write(clearText);
    writer.Flush();
    inStream.Position = 0;
    using var encryptedStream = new MemoryStream();
    
    EncryptAndSign(clearStream, encryptedStream, File.OpenRead(publicKey), 
        File.OpenRead(signatureKey), signatureKeyPassword, string.Empty);
    
    encryptedStream.Position = 0;
    var encryptedActual = new StreamReader(encryptedStream).ReadToEnd();
    encryptedStream.Position = 0;
    
    Assert.NotEqual(clearText, encryptedActual);
    Assert.True(encryptedActual.Contains("begin pgp message", StringComparison.InvariantCultureIgnoreCase));
    
    DecryptAndVerify(encryptedStream, clearStream, 
        File.OpenRead(publicSignatureKey), File.OpenRead(privateKey), privateKeyPassword, string.Empty);
    encryptedStream.Position = 0;
    clearStream.Position = 0;

    var clearActual = new StreamReader(clearStream).ReadToEnd();
    
    Assert.False(clearActual.Equals(encryptedActual, StringComparison.InvariantCultureIgnoreCase));
    Assert.True(clearActual.Equals(clearText, StringComparison.InvariantCultureIgnoreCase));
}

private void EncryptAndSign(Stream input, Stream output, Stream publicKey, Stream privateKey, string password, string correlationId)
{
        var tempStream = new MemoryStream();
        
        var encKey = new EncryptionKeys(publicKey);
        var pgpEnc = new PGP(encKey);
        pgpEnc.EncryptStream(input, tempStream);
        
        logger.LogTrace("Encrypting complete {correlationId}", correlationId);

        tempStream.Position = 0;
        
        var sigKey = new EncryptionKeys(privateKey, password);
        var pgpSign = new PGP(sigKey);
        
        pgpSign.SignStream(tempStream, output);
}

private void DecryptAndVerify(Stream input, Stream output, Stream publicSignatureKey, Stream privateEncKey,
    string password, string correlationId)
{
    var encKey = new EncryptionKeys(publicSignatureKey, privateEncKey, password);
    var pgp = new PGP(encKey);

    pgp.DecryptStreamAndVerify(input, output);
}
```

Interestingly, I am using this 2 step approach for `EncryptAndSign` because if I use the `PGP.EncryptStreamAndSign` from the library and write the file to disk, I do not see a signature on the file. This 2 step approach makes sure there's a signature on the file (using GPG Keychain on MacOS), but brings up the cast issue. 

It's possible I'm misunderstanding something here, I had great luck with this library until a vendor changed a requirement for us to sign with the same key pair they use to encrypt our content, so hopefully this is something dumb I'm doing.

**Comment by mattosaurus** [comment]
Hi, thanks for posting an example. I'll take a look at this when I get a chance.

**Comment by DanWillman** [comment]
If it helps, I've had some time to dig in and do a bit of research. When doing decryption/verification, the PgpObjectFactory first has a `PgpOnePassSignatureList` which brings us to the `NextPgpObject` call on PGP.cs:5208 which is where I get the PgpLiteralData object that fails the cast. 

It looks to me like DecryptAndVerify is doing the same initial steps as Decrypt and this probably just needs to be updated to expect the layout of a OnePassSignatureList and then the LiteralData. But I'm still working on catching up on how the underlying PGP things work, so I might be off.

**Comment by mattosaurus** [comment]
Hi, sorry for the delay on this.

So the issue is that although the `EncryptAndSign` methods sound like they will first encrypt the message and then add a seperate signature to it, what actually happens is that the signature of the original message is included within the encrypted message.

https://docs.oracle.com/cd/E55956_01/doc.11123/user_guide/content/encryption_pgp_enc.html

When you `Encrypt` and then `Sign` in your 2 step method you're actually just signing the encrypted file which doesn't verify that you authored the message within it. When you use `DecryptAndVerify` on this file it then throws a (rather unhelpful) error as it sees a signed file but is expecting an encrypted file with an integrated signature.

This isn't as intuative as it could be so I might update the docs to try and make this clearer.

**Comment by DanWillman** [comment]
Thanks for confirming, I actually did come to more or less that same conclusion in my own suite of testing, so it's nice to get validation on it. Some documentation around that might be nice as well.

**Comment by Liam-Rougoor** [comment]
Hi @mattosaurus 
In the latest version (5.10) I also run into the problem that if I first encrypt, then sign a message, the decryption fails:
`Unable to cast object of type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpLiteralData' to type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpEncryptedDataList'`

It looks like the PgpSignatureDataList is somehow casted to LiteralData, but the decrypt method doesn't proceed to read and decrypt the message within that signature. Do you know what might cause this issue?

If you need an example, I could create a repro project soon.

**Comment by mattosaurus** [comment]
It's possible to to decrypt an encrypted and then signed message using the following code.

```
// Arrange
TestFactory testFactory = new TestFactory();
await testFactory.ArrangeAsync(KeyType.Generated, FileType.GeneratedMedium);

EncryptionKeys encryptionKeys = new EncryptionKeys(testFactory.PublicKey);
EncryptionKeys signingKeys = new EncryptionKeys(testFactory.PrivateKey, testFactory.Password);

PGP pgpEncrypt = new PGP(encryptionKeys);
PGP pgpSign = new PGP(signingKeys);

// Act
string encryptedContent = await pgpEncrypt.EncryptArmoredStringAsync(testFactory.Content);
string signedContent = await pgpSign.SignArmoredStringAsync(encryptedContent);
VerificationResult verificationResult = await pgpEncrypt.VerifyAndReadSignedArmoredStringAsync(signedContent);
string decryptedContent = await pgpSign.DecryptArmoredStringAsync(verificationResult.ClearText);
```

I've updated the documentation to make the difference between EncryptAndSign and Encrypt then Sign more explicit. I think an error message is correct here as you're trying to decrypt a signed rather than encrypted file but I agree that the current one is not particularly useful so I'll try and focus on error messages for my next set of updates.
