### ISSUE TITLE
PGP encryption

### ISSUE THREAD

**Issue by mafia9874123** [mattosaurus/PgpCore#182]
Hi, I'm using PGPCore to encrypt some files. PGP public key have type Ed25519 (EdDSA - 255 bit). When I try to encrypt it returned "unknown PGP public key algorithm".

Is there anyway to work around it?

**Comment by mattosaurus** [comment]
Hi, looks like this hasn't made it into the Bouncy Castle library yet which PgpCore is based on.

https://github.com/bcgit/bc-csharp/issues/345

Not sure what you can do to get around this other than commenting on the issue to see if they've made any progress. When Bouncy Castle is updated I'll update PgpCore.

**Comment by mafia9874123** [comment]
Hi, @mattosaurus look like author of Bouncy Castle library have updated library to support EdDSA. 
https://github.com/bcgit/bc-csharp/commit/7f43ba84bd30b99d0e957920aa660a45f998c522

**Comment by mattosaurus** [comment]
Nice. They still need to create a release and publish the updated package to NuGet and then I'll update PgpCore accordingly.

**Comment by mattosaurus** [comment]
I've just published v5.9 which uses an updated version of bouncy castle. Hopefully that will solve your issue.

**Comment by mafia9874123** [comment]
Thanks, I have resolved my issue
