### ISSUE TITLE
Error Invalid Armor 

### ISSUE THREAD

**Issue by GuingaroMarcos** [mattosaurus/PgpCore#188]
I'm trying to decrypt a file, but it's returning the error 'Invalid Armature', but the armaduda is valid because I've already decrypted it before.

The code: 
![image](https://user-images.githubusercontent.com/84862087/202730054-4373d83a-0f1b-4ee1-8997-cd362c374052.png)

**Comment by GuingaroMarcos** [comment]
Hi, yes I used Didisoft and it worked normally.  Sorry, but the data is sensitive I don't have permission to disclose.

**Comment by mattosaurus** [comment]
No worries, you might need to clone the project and try and debug it yourself then if you can't share a working example with me then.

You could also try using some older versions of PgpCore as it's possible something has changed betweeen versions and that may provide some clues.
