### ISSUE TITLE
Change password / passphrase

### ISSUE THREAD

**Issue by jkiebzak** [mattosaurus/PgpCore#189]
If I create a set of keys like this:
```
using (PGP pgp = new PGP())
{
	// Generate keys
	pgp.GenerateKey(@"C:\TEMP\Keys\public.asc", @"C:\TEMP\Keys\private.asc", "email@email.com", "password");
}
```

Can I later change the password of the keys? If so, how?

**Comment by mattosaurus** [comment]
Sorry, there's not really any functionality for managing passphrases built into PgpCore. It's assumed that these will most likely be generated elsewhere and then used for processing with the library.

If you'd like to submit a PR with this functionality though please feel free.
