### ISSUE TITLE
Encryption Shows Completed but New File doesn't finish rendering

### ISSUE THREAD

**Issue by khalifclark** [mattosaurus/PgpCore#190]
I am using this library to create a process to encrypt txt files over to a client.  During my testing, I noticed that the new file appears the the encrypted data wasn't completely there after running EncryptFileAsync.  I am using a script task in Visual Studio SSDT to accomplish this need.  I just built it based off the EncryptFileAsync code that was on the github.  After it is all done, I wait like a few mins for the encryption to actually complete and sometimes the file is cutoff.  

[https://github.com/mattosaurus/PgpCore#encryptfileasync](url)

**Comment by mattosaurus** [comment]
You're probably not awaiting the async methods until completion.
