### ISSUE TITLE
 BouncyCastle Encryption to make it compatible with PGP 6.5.8

### ISSUE THREAD

**Issue by paritoshnagar2016** [mattosaurus/PgpCore#192]
is there any way  for BouncyCastle Encryption to make it compatible with PGP 6.5.8.

We have been encrypting file and our vendor is unable to decrypt and they found that is there way to make it compatible with PGP 6.5.8

**Comment by mattosaurus** [comment]
What makes you think it's incompatiable?

If you encrypt with PgpCore you should be able to decrypt with command line PGP.
