### ISSUE TITLE
Remove version from encrypted file

### ISSUE THREAD

**Issue by paritoshnagar2016** [mattosaurus/PgpCore#193]
is there any way to when file is encrypted the below version line should not show up

Version: BouncyCastle.NET Cryptography (netstandard2.0) v2.0.0+4f800b4d32

**Comment by mattosaurus** [comment]
Hi, the version header is added by the Bouncy Castle [ArmouredOutputStream](https://github.com/bcgit/bc-csharp/blob/b03a3283f3c1cc258db6a5697074c86071a40233/crypto/src/bcpg/ArmoredOutputStream.cs).

It looks like it might be possible to null out the version but not to remove the line entirely. If you want to do that the best way is probably to edit the encrypted file after it's been created to remove the line from it yourself, not a nice solution but it should work.

**Comment by paritoshnagar2016** [comment]
ok Thank you
