### ISSUE TITLE
The question of functionality

### ISSUE THREAD

**Issue by bvadeveloper** [mattosaurus/PgpCore#2]
Hi, is there any possibility to add encrypt/decrypt memory stream methods in current realization?
Thanks)

**Comment by mattosaurus** [comment]
Hi @bvadeveloper,

This should be doable. Were you thinking of something like the below?

```
            using (PGP pgp = new PGP())
            {
                // Decrypt stream
                using (FileStream inputFileStream = new FileStream(@"C:\TEMP\keys\content__encrypted.pgp", FileMode.Open))
                using (Stream outputFileStream = File.Create(@"C:\TEMP\keys\content__decrypted.txt"))
                    pgp.DecryptStream(inputFileStream, outputFileStream, @"C:\TEMP\keys\private.asc", "password");
            }
```

You would pass it an input and output stream and the key location would remain a path.

Thanks

Matt

**Comment by bvadeveloper** [comment]
Hi, thanks for the answer. Yep, I had thought about it and implement my own realization. Also in current realization, we have a small gap when we "encrypt and sign"  file\stream without compressing and trying to decrypt data. On my mind, we should implement decrypt in this way:

[PGP.zip](https://github.com/mattosaurus/PgpCore/files/1305793/PGP.zip)

**Comment by mattosaurus** [comment]
Hi, I've updated the code and NuGet package now to include EncryptStream and DecryptStream methods. Thanks for the suggestion.
