### ISSUE TITLE
Issues at client while they are decrypting the file

### ISSUE THREAD

**Issue by paritoshnagar2016** [mattosaurus/PgpCore#208]
One of our client is unable to decrypt the file as its giving error Secret key not found. 

We are using pgpcore library to encrypt the file using their public key that is PGP 6.5.8 1024 bit key. Do you know if there is any compatibility issues

**Comment by mattosaurus** [comment]
There shouldn't be an incompatibility issue. Most likely reason for the error is that your client is using the public key instead of the private key to decrypt the file.

**Comment by paritoshnagar2016** [comment]
but the client is able to decrypt other Trading Partner file

**Comment by mattosaurus** [comment]
Are you able to decrypt the file yourself (if you have access to the private key)?

Can they decrypt the file if you encrypt it with a different tool rather than PgpCore?
