### ISSUE TITLE
General help question - can this PGP be used as GPG 

### ISSUE THREAD

**Issue by sirfamol85** [mattosaurus/PgpCore#209]
I see command line queries shows gpg and then parameters where as this is implementation of PGP. I see PGP and GPG both are compatible in general. Is this package also compatible ? May be good question will be , if someone is expecting GPG encrypted files, can you send PGP encrypted files via this package ?

**Comment by mattosaurus** [comment]
Hi, yes, PGP and GPG are different implementations of the same standards so should be compatible with each other.

**Comment by sirfamol85** [comment]
Thanks.
