### ISSUE TITLE
Encrypt file only with public key

### ISSUE THREAD

**Issue by ArkadiuszZwierz** [mattosaurus/PgpCore#211]
Hello, 

Is any possibility to encrypt file, only using passphase and public key? Why private key is required to encrypt file, when private key should be used only in decryption?

Greetings

**Comment by mattosaurus** [comment]
You only need the public key to encrypt a file.

https://github.com/mattosaurus/PgpCore#encrypt

**Comment by ArkadiuszZwierz** [comment]
My mistake, thank you. I pass to EncryptionKey(publicKey, "", passPhase) and getting error from validators. 
Next time I need to read carefully documentation.
