### ISSUE TITLE
Getting NullReferenceException

### ISSUE THREAD

**Issue by autumnleaf73** [mattosaurus/PgpCore#216]
Hi Matt,

I am getting a NullReferenceException when I took your sample code to test your library:

``  
        // Load keys
        EncryptionKeys encryptionKeys;
        using (Stream publicKeyStream = new FileStream(keyfilePath, FileMode.Open))
            encryptionKeys = new EncryptionKeys(publicKeyStream, "*****");  //masked out 

        PGP pgp = new PGP(encryptionKeys);

        // Reference input/output files
        using (FileStream inputFileStream = new FileStream(plaintextFilePath, FileMode.Open))
        using (Stream outputFileStream = File.Create(@"C:\TEMP\encrypted.pgp"))
            // Encrypt
            await pgp.EncryptStreamAsync(inputFileStream, outputFileStream);   <- this is where the exception happened.
''
The inputFilestream has content with 13873  bytes in length. I don't think it is the reading of the file.  The private Key seems to have been read correctly. 

What could be the issue?

Trying to bring up the stack trace, it's telling me the issue is with "External code".

I am testing with PgpCore 5.10.0, BouncyCastle.Cryptography 2.1.1 has been loaded. I am testing this in a Console Windows within Visual Studio running .Net 6.0
Attached is a test sample file

Would you be able to help? Thank you so much.

 
[SampleCSVTestFile-small.txt](https://github.com/mattosaurus/PgpCore/files/11786123/SampleCSVTestFile-small.txt)

**Comment by autumnleaf73** [comment]
![issues-NullReferenceException](https://github.com/mattosaurus/PgpCore/assets/42158611/868f9de7-6d6b-449e-92ae-908eeb06efd4)

Attached is a screen shot of the exception thrown within Visual Studio.

**Comment by mattosaurus** [comment]
I think the issue is that you're using `encryptionKeys = new EncryptionKeys(publicKeyStream, "*****")` but that's for loading private keys so when you come to encrypt there is no public key available.

https://github.com/mattosaurus/PgpCore/blob/a3d8a62e4a1320195142e70bbd31d1e8fba23ef8/PgpCore/EncryptionKeys.cs#L211-L219

You should be using `encryptionKeys = new EncryptionKeys(publicKeyStream)`

https://github.com/mattosaurus/PgpCore/blob/a3d8a62e4a1320195142e70bbd31d1e8fba23ef8/PgpCore/EncryptionKeys.cs#L326-L334

**Comment by autumnleaf73** [comment]
Hi Matt,
The use case we have is to use the private key to encrypt the message and the recipient of the message will be using our public key to decrypt it. This is part of the B2B exchange of information. Thus I have the need to encrypt data using private key. What can I do in this case?

**Comment by mattosaurus** [comment]
Hi,

Unfortunatly that's not how PGP encryption works. The public key is intended to be shared and is used for encrypting the message, the private key should not be shared and is used to decrypt (and sign) the message.

What you may be looking for is [encrypt and sign](https://github.com/mattosaurus/PgpCore#encryptstreamandsignasync) where you encrypt with the recipients public key and then sign the message with your private key. They can then verify the message using your public key and decrypt it using their private key.

**Comment by autumnleaf73** [comment]
Thank you Matt,

I have re-visited the logic.  Now I am using the method as you have advice, EncryptStreamAndSignAsync().  I have a 3rd party public key, our private key and passphrase. upon, executing the function  EncryptStreamAndSignAsync(), an exception is thrown as follow:
``
"   at Org.BouncyCastle.Bcpg.OpenPgp.PgpEncryptedDataGenerator.Open(Stream outStr, Int64 length, Byte[] buffer)\r\n   at PgpCore.PGP.<OutputEncryptedAsync>d__277.MoveNext()\r\n   at PgpCore.PGP.<EncryptStreamAndSignAsync>d__86.MoveNext()\r\n   at Tattarang.Integration.Encryption.PgpEncryption.<EncryptAndSignAsync>d__8.MoveNext() in C:\\Users\\elim\\source\\repos\\IT_Integration_Common_Dotnet\\src\\Tattarang.Integration.Encryption\\PgpEncryption.cs:line 174\r\n   at Tattarang.Integration.Encryption.PgpEncryption.<EncryptAndSignAsync>d__7.MoveNext() in C:\\Users\\elim\\source\\repos\\IT_Integration_Common_Dotnet\\src\\Tattarang.Integration.Encryption\\PgpEncryption.cs:line 156\r\n   at Tattarang.Integration.Encryption.PgpEncryption.<EncryptAndSignAsync>d__6.MoveNext() in C:\\Users\\elim\\source\\repos\\IT_Integration_Common_Dotnet\\src\\...
``
with the exception message "No encryption methods specified" being given.

Here is my code snippet:
```
        private static async Task<Stream> EncryptAndSignAsync(Stream inputStream, EncryptionKeys encryptAndSignKeys)
        {
            Stream outputStream;

            using (PGP pgp = new PGP(encryptAndSignKeys))
            {
                outputStream = new MemoryStream();

                 await pgp.EncryptStreamAndSignAsync(inputStream, outputStream); // <--- exception thrown calling this 
                 outputStream.Seek(0, SeekOrigin.Begin);
            }
            return outputStream;
        }
``
What could the problem be?  What have I missed ? I am thinking my code look very similar to your example code. I can't figure out what seem to be the issue.

Thank you so much for your help.
