### ISSUE TITLE
PGP generate key with 2 years of expiration. 

### ISSUE THREAD

**Issue by patel-rohit** [mattosaurus/PgpCore#217]
The following cryptographic standards are required for PGP keys. Can anyone help to generate a key with the following requirement?

Key                        : RSA
Bit Strength: 2048
Key Expiry: Expires within 2 years

**Comment by tadkison** [comment]
when I generate keys using Kleopatra, nothing works to decrypt them using pgpcore (C#)   is there a way to configure this to work?

**Comment by mattosaurus** [comment]
Hi @tadkison, could you open a new issue rather than continuing with this unrelated one and post  the cod you're using as well as sample public/private keys, password and encrypted file to help me investigate the issue.

**Comment by tadkison** [comment]
@mattosaurus   will do.  I think I found a way to do this in gnugpg   https://dev.gnupg.org/T6422     I have to remove the AEAD from the generated Key.  that allowed it to be decrypted using pgpcore (nothing wrong with your code, just the keys being generated were not good)   thanks for the quick reply!
