### ISSUE TITLE
PGP command line to PGPCore?

### ISSUE THREAD

**Issue by MB34** [mattosaurus/PgpCore#223]
We're using batch files out of process to run these PGP commands to encrypt and sign files.

```
pgp --encrypt "%1" --recipient %2 --sign --output "%3" --passphrase "%4" --default-key "%5"

pgp --encrypt "%1" --recipient %2 --output "%3" --default-key "%4"
```

What should I be using in PGPCore to accomplish the same?
Unsure how to handle the keyID thing...

We currently use a keyring but have found that PGPCore doesn't like using it, we get the old Checksum exception when using it, so we will be modifying our process to use key files, instead.

**Comment by mattosaurus** [comment]
Hi, I'm currently on holiday for the next 2 weeks so won't be able to look at this in detail.

Yeah, adding support for keyrings is currently on my to-do list. It should work with a key file though, it'll try and pick the right key based on the use case but you can specify the particular key with the ID if required.
