### ISSUE TITLE
issue while decrypting binary file

### ISSUE THREAD

**Issue by vishalgabhraniCapgemini** [mattosaurus/PgpCore#230]
I am working in C# code. I generated the keys in binary format. Encryption is working fine but while decrypting binary file I am facing "unknown object in stream 47". 

I am reading key and encrypted file from local directory and also saving the decrypted stream in local directory.

Could anyone help me how can I decrypt binary file in C# code?

**Comment by mattosaurus** [comment]
Hi,

If you can provide me with the code you're using so I can replicate this I'll take a look next week.

A set of test keys and file would also help out if it's possible to provide them.
