### ISSUE TITLE
PgpCore open for Hacktoberfest?

### ISSUE THREAD

**Issue by Liam-Rougoor** [mattosaurus/PgpCore#232]
Hi!

I'll be participating in [Hacktoberfest](https://hacktoberfest.com/) and would like to contribute on PgpCore where I can (I've opened some issues I've encountered in my own projects).

I was wondering if you could add the hacktoberfest label/topic to the repo, so that it would count for Hacktoberfest? It might also attract other participants to contribute to the project.

**Comment by mattosaurus** [comment]
Good idea, always happy to have more contributors to help spread the load :)

I've added the hacktoberfest topic and I might see if I can draw up a list of issues/improvements.
