### ISSUE TITLE
Improve key generation

### ISSUE THREAD

**Issue by mattosaurus** [mattosaurus/PgpCore#239]
Currently key generation is pretty basic (mostly I assume you'll bring your own keys) however it would be good to improve this. First step would probably be to allow expiration dates.

#184

**Comment by Liam-Rougoor** [comment]
Hi! I noticed that allowing expiration dates is already implemented in #234 

What additional improvements do you need for this issue?

**Comment by mattosaurus** [comment]
Ah yes, so it does.

I'll close this and the underlying issue then.
