### ISSUE TITLE
Refactor PGP class

### ISSUE THREAD

**Issue by mattosaurus** [mattosaurus/PgpCore#241]
The PGP class is a bit of a beast and should probably be refactored. Potentially the best option is to split it into partial classes in line with the interfaces but I'm open to other options.

**Comment by Liam-Rougoor** [comment]
Do you mean, turn split PGP into `partial class PGP`es? An alternative could be to have separate classes that implement the necessary interfaces (for example, `PGPEncrypter`, `PGPSigner` etc.) and let PGP be a composite of those classes.

Main benefit is that main functionalities become more isolated, and can be tested and used in isolation if desired.
