### ISSUE TITLE
Size differences between files encrypted with PGPCore and files encrypted with PGP command line

### ISSUE THREAD

**Issue by MB34** [mattosaurus/PgpCore#248]
We have noticed that the files that are encrypted using PGPCore are significantly larger than files encrypted with command line PGP.

For a 22KB (22,304 bytes) file, the encrypted file size for one encrypted by command line PGP is 7.98KB (8,178 bytes)
But the exact same file encrypted using PGPCore is 78.2KB (80,087 bytes)

Can you explain this ten fold increase in file size?

**Comment by mattosaurus** [comment]
It's probably because PGP is compressing the message and the PGPCore default is not to compress it.

https://github.com/mattosaurus/PgpCore#compressionalgorithm

There may also be a difference in armoured vs binary output.

**Comment by MB34** [comment]
Well, how do I change the CompressionAlgorithm?

**Comment by mattosaurus** [comment]
https://github.com/mattosaurus/PgpCore/blob/82987094eec5f0f4d8856595a3083eb0257442ff/PgpCore.Tests/UnitTests/UnitTestsAsync.cs#L565-L598

**Comment by MB34** [comment]
THX, Got it working
