### ISSUE TITLE
Nuget publishing?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [mattosaurus/PgpCore#249]
Is there a reason the last 2 versions are not published to nuget.org?

![image](https://github.com/mattosaurus/PgpCore/assets/15063294/797c3d11-48a5-48a2-b659-16262de4b799)

**Comment by mattosaurus** [comment]
I was planning on pushing out all the updates in a single release.

There's still a few changes I'd like to make but I've published v5.13.0 with the changes made so far.
