### ISSUE TITLE
SignStreamAsync without armor results in closed outputstream

### ISSUE THREAD

**Issue by rinzed** [mattosaurus/PgpCore#250]
When using SignStreamAsync with armor set to false, the outputstream is disposed after the task completes.

Here is a sample of what I try to do:
```csharp
var encryptionKeys = new EncryptionKeys(privateKey: privateKey, passPhrase: _passPhrase);
using var pgp = new PGP(encryptionKeys);

await using var inputStream = new MemoryStream(Encoding.ASCII.GetBytes("Hello World!"));
inputStream.Position = 0;

await using var outputStream = new MemoryStream();

await pgp.SignStreamAsync(inputStream, outputStream, armor: false);
outputStream.Seek(0, SeekOrigin.Begin); // System.ObjectDisposedException: Cannot access a closed Stream.
```
When trying to get the outputSteam data it fails, because the stream has been disposed.

When armor is left on true, the outputstream is working correctly.

A workaround is to fetch the byte[] directly from the Stream using `outputStream.ToArray()`.

EDIT:
I was using v5.10.0, but after upgrading to v5.13.0, the same error still exists.

**Comment by mattosaurus** [comment]
Hi, this should be fixed in v5.13.1 which I've just published
