### ISSUE TITLE
GPG Compatibility

### ISSUE THREAD

**Issue by ben-foster-cko** [mattosaurus/PgpCore#26]
Hi,

First of all, great job on the library, it certainly takes the pain out of using the BouncyCastle APIs directly.

It looks like others have run into this issue but it seems that I can't sign and verify (+ encrypt/decrypt variants) when using keys generated using gpg. I am however able to encrypt and decrypt without signing/verifying.

I'm using the gpg command line tool and

```
gpg --generate-key 
```

To generate the key pairs. Then the following commands to export the keys so I can use them in my test app:

```
gpg --export -a --openpgp test@testing.com > test_pub.asc 
gpg --export-secret-key -a --openpgp test@testing.com > test.asc
```

I figured it may be a compatibility issue with PGP hence the `--openpgp` flag but this doesn't seem to make a difference.

Keys generated with https://pgpkeygen.com/ do work as expected.

Also, on a different topic, would you be open to a PR that makes the library truly async as currently the sync calls are just being wrapped in a Task.Run?

**Comment by mattosaurus** [comment]
Yes, I've so far been stumped by the GPG issue, I need to have a look into it again when I have more time but so far I've been using the library with PGP keys so it hasn't been a high priority for me.

I'm happy to accept a PR for making it properly async so feel free to submit one whenever you get a chance.

**Comment by mattosaurus** [comment]
This seems to have been due to not scanning the sub-keys of a signature for the public key ID to compare against. I've updated the code, tests and package now and it works as expected for keys I've generated using GPG. Let me know if it works for you now or if you're still experiencing issues.

**Comment by EmperorCy** [comment]
I don't know if is the same problem.
I encrypt and sign files also with keys from https://pgpkeygen.com/. 
With "pgp4win" encrypt/sign and decrypt/verify ok.

Within my C# app:
When i decrypt without sign is ok.
When i go to decrypt/verify a signed file, I get error **"Failed_ to verify".**
I debug and see that publicKey.KeyId and publicKeyED.KeyId is not same in function "verify".

Could you advise me if make something wrong? 
The library have any function make trust the public key like pgp4win??

**Comment by mattosaurus** [comment]
What version of the package are you using? I just updated it to v1.7.0 this morning to fix this issue.

I just ran the unit tests using a key pair generated at https://pgpkeygen.com/ and they all passed so hopefully this update has fixed your issue.

**Comment by EmperorCy** [comment]
I couldn't install because my app is in ".NETFramework,Version=v4.0"
I had download the file "PGP" and "EncryptionKeys" from repository.

**Comment by mattosaurus** [comment]
These files were updated yesterday as part of the v1.7.0 update, are you using the latest versions?

**Comment by EmperorCy** [comment]
Yes, I download today and the problem still the same.

**Comment by mattosaurus** [comment]
Are you able to create a test .NET Core application to see if it works when using the NuGet package?

**Comment by ben-foster-cko** [comment]
@mattosaurus thanks for this. I'll test and get back to you

**Comment by ben-foster-cko** [comment]
It works, thanks!
