### ISSUE TITLE
Provide FileName associated with the encrypted data stream

### ISSUE THREAD

**Issue by ayoussef-insight** [mattosaurus/PgpCore#281]
Provide a method to get the file name associated with the data stream when decrypting PGP file stream.

https://github.com/nano-byte/bc-csharp/blob/0e75b9e99168e9612ffe1eb3a21417c3a97764ca/crypto/src/openpgp/PgpLiteralData.cs#L38

**Comment by mattosaurus** [comment]
https://github.com/mattosaurus/PgpCore?tab=readme-ov-file#inspect
