### ISSUE TITLE
Error encrypting large file

### ISSUE THREAD

**Issue by rpedretti** [mattosaurus/PgpCore#29]
Hi.
I'm trying to encrypt/decrypt a large file (~7gb) but I'm getting a error
```Unhandled Exception: System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Org.BouncyCastle.Bcpg.BcpgOutputStream.PartialFlush(Boolean isLast)
   at Org.BouncyCastle.Bcpg.BcpgOutputStream.WritePartial(Byte[] buffer, Int32 off, Int32 len)
   at PgpCore.Utilities.PipeStreamContents(Stream input, Stream pOut, Int32 bufSize)
   at PgpCore.PGP.EncryptStream(Stream inputStream, Stream outputStream, IEnumerable`1 publicKeyStreams, Boolean armor, Boolean withIntegrityCheck)
   at PgpCore.PGP.<>c__DisplayClass25_0.<EncryptStreamAsync>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at PgpCore.PGP.EncryptStreamAsync(Stream inputStream, Stream outputStream, Stream publicKeyStream, Boolean armor, Boolean withIntegrityCheck)
   at PgpProcessor.Encrypt(String pubKeyPath, String inputFilePath, String outputFilePath) in C:\AgodaGit\aes\dotnet\PgpProcessor.cs:line 15
   at aes.Program.Main(String[] args) in C:\AgodaGit\aes\dotnet\Program.cs:line 33
   at aes.Program.<Main>(String[] args)
```

Created a bufferSize to output buffer but didn't work

```
using System.IO;
using System.Threading.Tasks;
using PgpCore;

public class PgpProcessor
{
    private const int bufferSize = 8 * 1024;

    public static async Task Encrypt(string pubKeyPath, string inputFilePath, string outputFilePath)
    {
        using (PGP pgp = new PGP())
        using (FileStream inputFileStream = new FileStream(inputFilePath, FileMode.Open))
        using (Stream outputFileStream = File.Create(outputFilePath, bufferSize))
        using (Stream publicKeyStream = new FileStream(pubKeyPath, FileMode.Open))
            await pgp.EncryptStreamAsync(inputFileStream, outputFileStream, publicKeyStream, false, false);
    }

    public static async Task Decrypt(string privKeyPath, string password, string inputFilePath, string outputFilePath)
    {
        using (PGP pgp = new PGP())
        using (FileStream inputFileStream = new FileStream(inputFilePath, FileMode.Open))
        using (Stream outputFileStream = File.Create(outputFilePath, bufferSize))
        using (Stream privateKeyStream = new FileStream(privKeyPath, FileMode.Open))
            await pgp.DecryptStreamAsync(inputFileStream, outputFileStream, privateKeyStream, password);
    }
}
```

Thanks!

**Comment by mattosaurus** [comment]
Hi,

I've only been using this with small files so far so haven't run into this before, I'll create a large file and investigate when I get a chance.

**Comment by mattosaurus** [comment]
It might be connected to this.

http://bouncy-castle.1462172.n4.nabble.com/When-encrypting-large-files-Exception-of-type-System-OutOfMemoryException-was-thrown-td3249165.html

Will try and change to base it on this instead.

https://github.com/bcgit/bc-csharp/blob/f18a2dbbc2c1b4277e24a2e51f09cac02eedf1f5/crypto/test/src/openpgp/examples/KeyBasedLargeFileProcessor.cs

**Comment by mattosaurus** [comment]
I've added in a fix based on the documentation above and have tested with a 7GB file which encrypted and decrypted as expected. These changes are available in v2.0.0 of the package.

There's a test in the test project for this now as well, though it's currently commented out as it takes so long to run!

**Comment by ajay2141** [comment]
I am unable to find latest package version v2.0.0 on nuget. Latest I can see is 1.8.9.

Can you confirm latest version v2.0.0 is published ?

**Comment by mattosaurus** [comment]
Hi @ajay2141, I'm not sure what package you're trying to load from NuGet but it's not PgpCore.

**Comment by ajay2141** [comment]
Hello @mattosaurus,

I am using bouncy castle version v1.8.9 to encrypt large file. Which is not working for me. 
My solution is build on .net framework 4.7.2 and I have only nuget added is BouncyCastle v1.8.9

**Comment by mattosaurus** [comment]
Are you using PgpCore to encrypt the files or have you built your own solution using BouncyCastle?

If you're not using PgpCore I suggest you raise an issue on the [BouncyCastle project](https://github.com/bcgit/bc-csharp).

**Comment by ajay2141** [comment]
Hello @mattosaurus,

I tried https://github.com/mattosaurus/PgpCore sample code with sample pdf. but did not worked for me either.

**Comment by mattosaurus** [comment]
You're probably closing the stream before the file has been fully decrypted.

Can you please open a new issue and provide me with a working code example.
