### ISSUE TITLE
Publish latest release to NuGet

### ISSUE THREAD

**Issue by phsym** [mattosaurus/PgpCore#291]
Hi ! Thank you for your work on this library, it's very useful.

The latest published release on NuGet is `v6.3.1` while the latest github release is `v6.4.1 `. Any chance to get it published to NuGet ?

Thanks in advance

**Comment by mattosaurus** [comment]
Hi, sorry for the delay. I've published 6.4.1 now.

**Comment by phsym** [comment]
Awesome, thank you
