### ISSUE TITLE
.net 8 upgrade

### ISSUE THREAD

**Issue by manjzu** [mattosaurus/PgpCore#299]
looks like current package is built using .net 6, is there any plans of upgrading code to .net 8?

**Comment by manjzu** [comment]
@mattosaurus 
version in the encrypted file seems to be showing description as .net6.0 "Version: BouncyCastle.NET Cryptography **(net6.0)** v2.4.0", which is deceiving.

**Comment by mattosaurus** [comment]
Ah, I see. The version info in the encrypted file comes from the underlying Bouncy Castle library which is built using .NET 6.

https://github.com/bcgit/bc-csharp/blob/41215d66a26f02d170bce5e0bdf052fdac1d7828/crypto/src/BouncyCastle.Crypto.csproj#L6

If desired you can set your own custom headers, which includes overwriting the version header.

https://github.com/mattosaurus/PgpCore/blob/93b2ff9bf18dcad0d3859bf20cd1dc3d66b0252b/PgpCore.Tests/UnitTests/Encrypt/EncryptSync.File.cs#L185-L217
