### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by FuncLun** [mattosaurus/PgpCore#36]
Have you thought about following Microsoft's guidance on providing strong-named assemblies for libraries? For some, strong-named libraries are required (e.g. COM objects), and StrongNamer does not work perfectly or in all scenarios. FYI, Portable.BouncyCastle is strong-named.

A tip to help those that strong-names causes issues: your AssemblyVersion does not have to change for each release. All 2.x.x.x releases can have AssemblyVersion 2.0.0.0, etc.

✔️ CONSIDER strong naming your library's assemblies.

✔️ CONSIDER adding the strong naming key to your source control system.

✔️ CONSIDER incrementing the assembly version on only major version changes to help users reduce binding redirects, and how often they're updated.

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

**Comment by mattosaurus** [comment]
I hadn't thought about this before as it's never been an issue for me, am happy to strong name it if it'll make things easier for other people though. Will probably look at adding this in the next update.

**Comment by mattosaurus** [comment]
The package is now strongly named from v2.1.0
