### ISSUE TITLE
Large memory usage when decrypting not-large file

### ISSUE THREAD

**Issue by scottpantall** [mattosaurus/PgpCore#39]
We are using `DecryptStreamAsync()` to decrypt a FileStream into a MemoryStream but when we do this with a 24MB FileStream we end up with a 1GB MemoryStream. However when decrypt a smaller FileStream (ie. 7.4KB) we end up with a similar-sized MemoryStream. What would cause this?

Attached are screenshots of the variables in question. `encryptedData` is the FileStream and `result` is the MemoryStream.

Thanks!

![24mbfilelocals-public](https://user-images.githubusercontent.com/4606914/65446331-59811780-ddf1-11e9-9902-594eb86c45a2.png)
![7kbfilelocals-public](https://user-images.githubusercontent.com/4606914/65446332-5a19ae00-ddf1-11e9-9c06-95532ae44f28.png)

**Comment by mattosaurus** [comment]
What version of the package are you using?

In v2+ I changed the way objects are handled in memory to better deal with large files so it's possible this has pushed the memory usage up. Are you able to compare the memory usage using the latest package (v2.1.0) and the last one before I made these changes (v1.7.2)?

**Comment by rillyboss** [comment]
We currently are using version 1.7.0. We will update the package and report back.

**Comment by rillyboss** [comment]
I believe we can safely close this. The reason our memory streams are so large is the that the resulting decrypted files are ~600MB : ~1GB. 
Thank you for the quick response!

**Comment by mattosaurus** [comment]
Excellent, glad to her it wasn't a bug :)
