### ISSUE TITLE
SignFile resulting structure is unexpected/ wrong

### ISSUE THREAD

**Issue by ccvca** [mattosaurus/PgpCore#40]
I'm using the following code for signing a file:

```cs
using PgpCore;
using System;
using System.IO;

namespace GpgTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Begin");

            string basePath = "";
            string fileBare = Path.Combine(basePath, @"testData\content.txt");
            string fileEncrypted = Path.Combine(basePath, @"testData\content.txt.encrypt.pgp");
            string fileSigned = Path.Combine(basePath, @"testData\content.txt.signed.pgp");

            Directory.CreateDirectory("keys");
            Directory.CreateDirectory("testData");
            File.WriteAllText(fileBare, "MyTestContent");
            using (PGP pgp = new PGP())
            {
                string KeyPub = Path.Combine(basePath, @"keys\public.asc");
                string KeyPriv = Path.Combine(basePath, @"keys\private.asc");
                string KeyPasswd = @"password";
                // Generate keys
                pgp.GenerateKey(KeyPub, KeyPriv, "email@example.com", KeyPasswd);
                
                pgp.SignFile(fileBare, fileSigned, KeyPriv, KeyPasswd, true, true);
            }

            Console.WriteLine("Done");
        }
    }
}
```

This produces a file with the following contents:
```
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.8.5.0

kA0DAAIBR2nEQUeYkD4Byx5iC2NvbnRlbnQudHh0XZNmFE15VGVzdENvbnRlbnSI
rwQAAQIAGQUCXZNJ9BIcZW1haWxAZXhhbXBsZS5jb20ACgkQR2nEQUeYkD4+JgP/
abO2vPjGj03J9AZe1OenyPdm/l+qN3xh++no8lqTW2t/KInhE8bnQyo2bNXLB+l0
FWt3AQRfMQYPRZ2wn6jcC+MolYc9dTQYbccsjv1nEeLOi5IbJ+i/Lk7h1B0EV2xU
xGXKNUGrs26eFVeFdLFkuZfnaHT+TVV1W3vYmpUPO6I=
=KIlz
-----END PGP MESSAGE-----
```

I would expect a file like the following (Signature/ Structure taken from http://apt.postgresql.org/pub/repos/apt/dists/bionic-pgdg/InRelease):
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

MyTestContent
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEuXsK/KoaR/BE8kSgf8x9RqzMTPgFAl2Mt24ACgkQf8x9RqzM
TPiFhw/8DM18ObaqnkX50G/T05EF4fTvbbfDIjSpHOP6eNCThC+FViuL74gcfSTv
FW2JtozWHo9Bm4V2AnoNCYSdc3cXIMcq8DVtaSY/ccR4s3CT6yo5oDKZT7/l5fkK
RJLlQuQdJzUKHEAzGx0jZQqY/E/jtNqS+BvIYlpPjwk3BLEzW4jqf5Lokf8eEgM5
ffnRE1plf8I8ciDcrUWsaQKGCPDAMFraqriT7pkB7y3rjrP77oFtU3VsZBUc2JS5
29A9/6fTLIGwSjcbXksQ88FXzENvE+MqIR4zojGLrg/vOlU08FjUuZUkAAhdQ0G6
PLlOBhn90JypFTfADfaGKK4DzUX1xOhQhbNNwXTDimkwjLYJb0waeen8vI0F4nnh
4I75fmBC4/mLLL0WnOYV3f12bFuZrA77+ispeUfsE24ZYiG68sVri7P1IWfAtMoZ
TaIWKblUZ2ZLOb223qEJNVvGGxuiJe3hXeifsFG4m/b9IPdiU8ZMe5knLbjNz3Sg
Plax2VVyESWA4kkol7TwhsjkfN1Mj4g5hrD6VckQ4M8UaXr2EvxpbjnIWMGrW7WM
fCOwiBfqiH9GMvTLpbgy/frMbMr/7Oc/4EOVLzHfid5yNd74aE5Z8rPUQhjNm1ah
j38FiIajeGq9/sFc9Xs2L6CNotaPNo3F0XcJpQLAXEPHwbID23k=
=GYF1
-----END PGP SIGNATURE-----
```

Looking at the ArmoredOutputStream from the underlying library, it is capable to create files with that structure:
https://github.com/bcgit/bc-csharp/blob/7248688e6f513cbdde1ccc1d39904cb964b0c88a/crypto/src/bcpg/ArmoredOutputStream.cs#L196
```cs
DoWrite("-----BEGIN PGP SIGNED MESSAGE-----" + nl);
```

https://github.com/bcgit/bc-csharp/blob/7248688e6f513cbdde1ccc1d39904cb964b0c88a/crypto/src/bcpg/ArmoredOutputStream.cs#L258-260
```cs
case PacketTag.Signature:
  type = "SIGNATURE";
  break;
```

Even if the current verison of the library should only save the signature (I do not get it from the function itself), this file should begin with "BEGIN PGP SIGNATURE" instead of "BEGIN PGP MESSAGE". But as the file is always larger than the encrypted one, I would suspect, that the content  signature are inside the file.

**Comment by mattosaurus** [comment]
Thanks, I hadn't spotted this. I'm on holiday at the moment so won't have a chance to look at this until next week. Feel free to submit a PR request if you'd like to speed this along.

**Comment by ccvca** [comment]
1.  Enjoy your holiday

As I do not have experience in encryption in deep, I'm probably unable to provide a pull request for this.

**Comment by mattosaurus** [comment]
I've had a look at this and unfortunately it doesn't seem to be that easy to fix as the signature generation occurs at quite a low level and it will need to change quite a bit to get it working.

I'll keep working on this as I can but I don't expect it to be a quick fix.

**Comment by clintnetwork** [comment]
+1 I just come to sign a random string and I get this:

```
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v1.8.6.0

kA0DAAIBYt4s2/8BkdwByx1iC0hlbGxvIHdvcmxkXrb4
```

It's not a well formated PGP Signature, I hope you could fix this quickly!
Anyway it's a really good and fluent PGP library

**Comment by mattosaurus** [comment]
I actually started having a look at this last week as I've now got more spare time due to lockdown, will report back when I've managed to fix this.

**Comment by mattosaurus** [comment]
I've published v2.4.0 of PgpCore to Nuget that has the following new methods.

- ClearSignFileAsync
- ClearSignFile
- ClearSignStream
- ClearSignStreamAsync
- VerifyClearStreamAsync
- VerifyClearStream
- VerifyClearFileAsync
- VerifyClearFile

These work fine as far as I can tell but let me know if you run into any issues.

**Comment by tkaradimitris** [comment]
Thank you for a great library!

ClearSign seems to have the desired functionality, as described by @ccvca, and as I tested with gpg4win (https://files.gpg4win.org/gpg4win-3.1.11.exe)

(Please note that gpg4win supports --sign command, which does return the same output as PgpCore.PGP.SignFile method, ie a PGP MESSAGE with mixed file contents and signature)

To extract the original contents of a file or stream, either signed, or clear-signed, gpg4win uses -d command (decrypt):
gpg -a --output inputFile.sig --sign inputFile.txt
gpg --output inputFile2.txt -d inputFile.sig

gpg -a --output inputFile.sig --clear-sign inputFile.txt
gpg --output inputFile2.txt -d inputFile.sig

PgpCore.PGP.DecryptFileAndVerify on the other hand, expects both a public key and a private key to operate, and 1) it fails if no private key is supplied (one is not needed simply to extract signed contents), and 2) even if a private key is supplied, it fails as it expects encrypted content.

```
// Sign file
pgp.SignFile(inputFilePath: inputFile, outputFilePath: signedFile, privateKeyFilePath: privateKeyFile, passPhrase: privatePassPhrase, armor: true, withIntegrityCheck: true);
Assert.True(File.Exists(signedFile), $"Signed file not found: {signedFile}");

// Verify file
bool verified = pgp.VerifyFile(inputFilePath: signedFile, publicKeyFilePath: publicKeyFile);
Assert.True(verified, $"Signed file could not be verified: {signedFile}");

// Decrypt file
pgp.DecryptFileAndVerify(inputFilePath: signedFile, outputFilePath: verifyFile, publicKeyFilePath: publicKeyFile, privateKeyFilePath: privateKeyFile, passPhrase: privatePassPhrase);

```

_Unable to cast object of type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpLiteralData' to type 'Org.BouncyCastle.Bcpg.OpenPgp.PgpEncryptedDataList'_

PgpCore.PGP.Decrypt does not seem useful either, as it does not accept a public key parameter.

What is the suggested method to extract data from signed or clear-signed files / streams?

**Comment by mattosaurus** [comment]
Hi @tkaradimitris, DecryptFileAndVerify is intended for decrypting and verifying encrypted and signed files which is why it requires both a public and private key. There's currently no functionality for extracting the clear signed content as I'd figured these message would mostly be being read by humans.

If this is something that you need then feel free to submit a PR if you're able, or if not I'll add it to my work list and get to it when I have a chance.

**Comment by tkaradimitris** [comment]
> Hi @tkaradimitris, DecryptFileAndVerify is intended for decrypting and verifying encrypted and signed files which is why it requires both a public and private key. There's currently no functionality for extracting the clear signed content as I'd figured these message would mostly be being read by humans.
> 
> If this is something that you need then feel free to submit a PR if you're able, or if not I'll add it to my work list and get to it when I have a chance.

Thank you @mattosaurus for the answer and the great work. I am not sure what I need to use from BouncyCastle to extract content from signed files / streams, but if I manage to find examples from other solutions I will try to submit a PR.

**Comment by JSingh-Dax** [comment]
Hi  Guys,

I am having an issue with decrypting the file.

I have encrypted the file using public key, private key and pass phrase.

When I am trying to decrypt the same file using the same key. I am getting the error message as "Secret message not found."

below is my code. I am using PGPCore.dll version 5.8.1

using System;
using System.IO;
using PgpCore;

namespace pgp
{
    class PGPHelper
    {
        static void Main(string[] args)
        {
            PGPHelper pgpHelper = new PGPHelper();
              pgpHelper.decrypt();
           // pgpHelper.encrypt();
        }


        void decrypt()
        {
            // Load keys
            FileInfo publicKey = new FileInfo(@"C:\Temp\Keys\TestPgpPublicKey.asc");
            FileInfo privateKey = new FileInfo(@"C:\Temp\Keys\0x0D086BB3-sec.asc");
            
            EncryptionKeys encryptionKeys = new EncryptionKeys(publicKey, privateKey, "mytestpassphrase");

            // Reference input/output files
            FileInfo inputFile = new FileInfo(@"C:\Temp\Content\encrypted.pgp");
            
            FileInfo decryptedFile = new FileInfo(@"C:\TEMP\Content\decrypted.txt");

            // Decrypt
            PGP pgp = new PGP(encryptionKeys);
            pgp.DecryptFile(inputFile, decryptedFile);
        }


        void encrypt()
        {

            // Load keys
            FileInfo publicKey = new FileInfo(@"C:\Temp\Keys\TestPgpPublicKey.asc");
            FileInfo privateKey = new FileInfo(@"C:\Temp\Keys\0x0D086BB3-sec.asc");
            EncryptionKeys encryptionKeys = new EncryptionKeys(publicKey, privateKey, "mytestpassphrase");

            // Reference input/output files
            FileInfo inputFile = new FileInfo(@"C:\Temp\Content\testFile.txt");
            FileInfo encryptedFile = new FileInfo(@"C:\TEMP\Content\encrypted.pgp");
            FileInfo signedFile = new FileInfo(@"C:\temp\content\signed.pgp");

            // Encrypt and Sign
            PGP pgp = new PGP(encryptionKeys);
            pgp.EncryptFileAndSign(inputFile, encryptedFile);
            pgp.VerifyFile(encryptedFile);
        }
    }
}
