### ISSUE TITLE
return decrypted data as a Stream (rather than file)

### ISSUE THREAD

**Issue by knaidoo33** [mattosaurus/PgpCore#42]
Hello @mattosaurus ,

Is it possible to return the decrypted data as a Stream (accessing outputStream) rather than as a file as you did in the test case?

// Test File example
            using (FileStream inputFileStream = new FileStream(contentFilePath, FileMode.Open))
            using (Stream outputFileStream = File.Create(encryptedContentFilePath))
            using (Stream publicKeyStream = new FileStream(publicKeyFilePath1, FileMode.Open))
            using (Stream privateKeyStream = new FileStream(privateKeyFilePath1, FileMode.Open))
                pgp.EncryptStreamAndSign(inputFileStream, outputFileStream, publicKeyStream, privateKeyStream, password1);

            using (FileStream inputFileStream = new FileStream(encryptedContentFilePath, FileMode.Open))
            using (Stream outputFileStream = File.Create(decryptedContentFilePath1))
            using (Stream privateKeyStream = new FileStream(privateKeyFilePath1, FileMode.Open))
                pgp.DecryptStream(inputFileStream, outputFileStream, privateKeyStream, password1);

            string decryptedContent = File.ReadAllText(decryptedContentFilePath1);

//My attempt at accessing the stream directly
//outputStream is  null

Stream outputStream = new MemoryStream();
            Stream privateKeyStream = GenerateStreamFromString(privateKey);

            var length = privateKeyStream.Length;
            var length2 = req.Body.Length;

            
            using (PGP pgp = new PGP())
            {
                

                using (Stream inputStream = req.Body)
                using(outputStream)
                using (privateKeyStream)
                {
                    inputStream.Seek(0, SeekOrigin.Begin);
                    privateKeyStream.Seek(0, SeekOrigin.Begin);
                    outputStream.Seek(0, SeekOrigin.Begin);
                    pgp.DecryptStreamAsync(inputStream, outputStream, privateKeyStream, passPhrase);
                    log.LogInformation($"decryption complete");
                    outputStream.Seek(0, SeekOrigin.Begin);
                    log.LogInformation($"seek complete");
                    var length3 = outputStream.Length;
                    log.LogInformation($"check stream: {length3}");
                    StreamReader reader = new StreamReader(outputStream);
                    string decryptedData = reader.ReadToEnd();
                    log.LogInformation($"read complete: {decryptedData}");
                    dynamic data = JsonConvert.DeserializeObject(decryptedData);
                    log.LogInformation($"convert complete:{data}");
                    return data != null
                            ? (ActionResult)new OkObjectResult(data)
                            : new BadRequestObjectResult("Data not found");
                    //return outputStream;
                }
            }

**Comment by knaidoo33** [comment]
I realized this could be because I was trying to run an Async method, so I tried this. I am now getting the "Secret key for message not found" error that I was getting before that I thought was fixed by seeking the start of the stream. It appears it may have only been succeeding because I had removed the await...

   private static async Task<Stream> DecryptAsync(Stream inputStream, Stream privateKeyStream, string passPhrase)
        {
            using (PGP pgp = new PGP())
            {
                Stream outputStream = new MemoryStream();

                using (inputStream)
                using (privateKeyStream)
                {
                    inputStream.Seek(0, SeekOrigin.Begin);
                    privateKeyStream.Seek(0, SeekOrigin.Begin);
                    outputStream.Seek(0, SeekOrigin.Begin);
                    await pgp.DecryptStreamAsync(inputStream, outputStream, privateKeyStream, passPhrase);
                    outputStream.Seek(0, SeekOrigin.Begin);
                    return outputStream;
                }
            }
        }

**Comment by mattosaurus** [comment]
Hi, the below work for me, both sync and async, let me know if they help.

```
[Theory]
[InlineData(KeyType.Generated)]
[InlineData(KeyType.Known)]
[InlineData(KeyType.KnownGpg)]
public void DecryptStream_DecryptEncryptedStream(KeyType keyType)
{
	// Arrange
	Arrange(keyType);
	PGP pgp = new PGP();

	// Act
	using (FileStream inputFileStream = new FileStream(contentFilePath, FileMode.Open))
	using (Stream outputMemoryStream = new MemoryStream())
	using (Stream publicKeyStream = new FileStream(publicKeyFilePath1, FileMode.Open))
	{
		pgp.EncryptStream(inputFileStream, outputMemoryStream, publicKeyStream);
		outputMemoryStream.Seek(0, SeekOrigin.Begin);

		using (Stream outputFileStream = File.Create(decryptedContentFilePath1))
		using (Stream privateKeyStream = new FileStream(privateKeyFilePath1, FileMode.Open))
			pgp.DecryptStream(outputMemoryStream, outputFileStream, privateKeyStream, password1);
	}

	string decryptedContent = File.ReadAllText(decryptedContentFilePath1);

	// Assert
	Assert.True(File.Exists(decryptedContentFilePath1));
	Assert.Equal(content, decryptedContent.Trim());

	// Teardown
	Teardown();
}

[Theory]
[InlineData(KeyType.Generated)]
[InlineData(KeyType.Known)]
[InlineData(KeyType.KnownGpg)]
public async Task DecryptStreamAsync_DecryptEncryptedStream(KeyType keyType)
{
	// Arrange
	Arrange(keyType);
	PGP pgp = new PGP();

	// Act
	using (FileStream inputFileStream = new FileStream(contentFilePath, FileMode.Open))
	using (Stream outputMemoryStream = new MemoryStream())
	using (Stream publicKeyStream = new FileStream(publicKeyFilePath1, FileMode.Open))
	{
		await pgp.EncryptStreamAsync(inputFileStream, outputMemoryStream, publicKeyStream);
		outputMemoryStream.Seek(0, SeekOrigin.Begin);

		using (Stream outputFileStream = File.Create(decryptedContentFilePath1))
		using (Stream privateKeyStream = new FileStream(privateKeyFilePath1, FileMode.Open))
			await pgp.DecryptStreamAsync(outputMemoryStream, outputFileStream, privateKeyStream, password1);
	}

	string decryptedContent = File.ReadAllText(decryptedContentFilePath1);

	// Assert
	Assert.True(File.Exists(decryptedContentFilePath1));
	Assert.Equal(content, decryptedContent.Trim());

	// Teardown
	Teardown();
}
```

If not how are you trying to use this, is it in an Azure function? If so I can see if I can knock up an example of how it should be used.

**Comment by knaidoo33** [comment]
Hi, thanks for the quick response. I am trying to use it in an Azure Function. If you could, that would be awesome. 
I found this other package that uses pgp core that seems like it may be working, however I'm not sure if the problem is that my files are gzipped before they are encrypted or if the output is strange because its not being used properly. I'm gonna be attempting to unzip the output today, 

https://github.com/lfalck/AzureFunctionsPGPDecrypt/issues/4

**Comment by mattosaurus** [comment]
I think it probably is because they're gzipped, you'll likely need to decompress them first and then decrypt them.

Something like [this](https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.gzipstream?view=netcore-2.2) may work which you can probably slot into the above Azure function.

```
using (GZipStream decompressionStream = new GZipStream(originalFileStream, CompressionMode.Decompress))
{
	decompressionStream.CopyTo(decompressedFileStream);
}
```

**Comment by knaidoo33** [comment]
got it! Thanks!

**Comment by knaidoo33** [comment]
Hi @mattosaurus, 

Thanks for all of your help so far.
I am attempting to get this working in a sync method again and I am running into problems... I was able to get it working with the help from the above package async.. but I have since realized U have a requirement for an out param that can only be used with a sync method. 

I am passing the same inpus to both of these functions.

//Async - working as expected

private static async Task<Stream> DecryptAsync(Stream inputStream, string privateKey, string passPhrase)
        {
            using (PGP pgp = new PGP())
            {
                Stream outputStream = new MemoryStream();

                

                using (inputStream)
                using (Stream privateKeyStream = GenerateStreamFromString(privateKey))
                {
                    await pgp.DecryptStreamAsync(inputStream, outputStream, privateKeyStream, passPhrase);
                    outputStream.Seek(0, SeekOrigin.Begin);
                    return outputStream;
                }
            }
        }


//Sync attempt - getting "Secret key for message not found" error
 private static Stream Decrypt(Stream inputStream, string privateKey, string passPhrase)
        {
            using (PGP pgp = new PGP())
            {
                Stream outputStream = new MemoryStream();

                
                using (inputStream)
                using (Stream privateKeyStream = GenerateStreamFromString(privateKey))
                {
                    //inputStream.Seek(0, SeekOrigin.Begin); 
                    //privateKeyStream.Seek(0, SeekOrigin.Begin);
                    pgp.DecryptStream(inputStream, outputStream, privateKeyStream, passPhrase);
                    //System.Threading.Thread.Sleep(30000);
                    outputStream.Seek(0, SeekOrigin.Begin);
                    return outputStream;
                }
            }
        }

**Comment by mattosaurus** [comment]
How does your GenerateStreamFromString function work, is it returning the end of the stream rather than having been reset to the start?

Using GetBytes as below successfully decrypts the content.

```
public void DecryptStream_DecryptEncryptedStream(KeyType keyType)
{
	// Arrange
	Arrange(keyType);
	PGP pgp = new PGP();

	// Act
	using (FileStream inputFileStream = new FileStream(contentFilePath, FileMode.Open))
	using (Stream outputFileStream = File.Create(encryptedContentFilePath))
	using (Stream publicKeyStream = new FileStream(publicKeyFilePath1, FileMode.Open))
		pgp.EncryptStream(inputFileStream, outputFileStream, publicKeyStream);

	Stream outputStream = new MemoryStream();

	using (FileStream inputFileStream = new FileStream(encryptedContentFilePath, FileMode.Open))
	using (Stream privateKeyStream = new MemoryStream(Encoding.UTF8.GetBytes(privateKey1)))
		pgp.DecryptStream(inputFileStream, outputStream, privateKeyStream, password1);

	outputStream.Seek(0, SeekOrigin.Begin);
	StreamReader reader = new StreamReader(outputStream);
	string decryptedContent = reader.ReadToEnd();

	Assert.Equal(content, decryptedContent.Trim());

	// Teardown
	Teardown();
}
```

**Comment by knaidoo33** [comment]
I was calling -

 private static Stream GenerateStreamFromString(string s)
        {
            MemoryStream stream = new MemoryStream();
            StreamWriter writer = new StreamWriter(stream);
            writer.Write(s);
            writer.Flush();
            stream.Position = 0;
            return stream;
        }

I tried your method of converting to string and that didnt work for me, but in the async code I was passing the private key as a base64 encoded string and converting, and in the sync code I was trying to pass it without encoding it first. 

I decided to try encoding it first and then decoding it this way - 

byte[] data = Convert.FromBase64String(privateKey);
            string privateKey1 = Encoding.UTF8.GetString(data);

and it works now! 

Thanks!!
