### ISSUE TITLE
Decrypting a very large file fails

### ISSUE THREAD

**Issue by imorital** [mattosaurus/PgpCore#45]
I'm trying to PGP decrypt a very large file via an Azure function using PgpCore, however whilst the output is processed quite quickly for test files (for example a 512Mb file gets decrypted in less than a minute) decrypting very large files (for example 20GB) fails.

We have a timeout on the Azure function of 6 hours, but the process never seems to complete.

The decryption code is quite simple:

```
using (Stream inputFileStream = await storageAccess.OpenFileStreamAsync(container, encryptedFilePath))
{
  using (Stream outputFileStream = await storageAccess.OpenWritableStreamAsync(container, outputFilePath))
  {
    using (Stream privateKeyStream = await GetPrivateKeyStream())
    {
      using (PGP pgp = new PGP())
      {
        logging.LogInformation($"Decrypting {encryptedFilePath} to {destinationDirectory}");

        pgp.DecryptStream(inputFileStream, outputFileStream, privateKeyStream, password);

        logging.LogInformation($"Decryption complete for {encryptedFilePath}");
      }
    }
  }
}
```

Where OpenWritableStreamAsync returns a blockBlob.OpenWriteAsync() and OpenFileStreamAsync returns a blockBlob.OpenReadAsync()

I've looked and I can't find any reference of the maximum size file that can be processed, let alone how to change this, or any examples of decrypting using buffered input streaming.

Is there something failing internally here, or is it just a case of taking over 6 hours or filling the available memory?

Thanks

**Comment by mattosaurus** [comment]
I assume you're using an app service plan to host this function rather than a consumption one as these timeout after 10 minutes?

What version of PgpCore are you using? I added in a fix (#29) for handling large files with release 2.0.0 so if you're using an older version this might be the cause.

Can you decrypt the file locally either in a console app or by debugging the Function? If not this implies it may be my library rather than the function and will hopefully give you a useful error.

Out of interest, why are you using a Function for this, I'd have thought it's probably better handled by a web job (even if you use a Function to trigger it)?

**Comment by imorital** [comment]
Hi,

Yes we're on an app service plan with the timeout set to 6 hours (we could possibly extend this) and using PGP Core version 2.1.0.

I'll try to get a copy of the file locally and see what happens. Will let you know.

Thanks.

**Comment by imorital** [comment]
In answer to your (very fair) question about why are we doing this as a function rather than a web job, we wondered that ourselves, but the architect on this project is fortunately very highly regarded so since it seemed possible (and in some ways quite neat) we were happy to go with this approach.

With hindsight that may not have been the best decision...

**Comment by mattosaurus** [comment]
Cool, figured it best to check the obvious stuff first :)

I've [tested for encrypting large files](https://github.com/mattosaurus/PgpCore/blob/31479efd143e4aa11b446851b33b5d36051b5d0a/PgpCore.Tests/UnitTests.cs#L203-L221) which all worked as expected but I haven't added a test for streams which conceivably could behave differently.

I certainly agree that running as a function could simplify things, I might have to give this a go in future projects.

**Comment by imorital** [comment]
I can confirm this is a false alarm, apologies.

Running in a local console app the file takes a little under two hours to decrypt. We made some changes to the code to use a temp location and better blob streaming and it all completes in Azure in a little under 3 hours now.

Can I also just say thanks for your rapid and helpful response to this, it really gives confidence in the library!
