### ISSUE TITLE
GenerateKey should overwrite file

### ISSUE THREAD

**Issue by blackboxlogic** [mattosaurus/PgpCore#46]
When generating a key, if the out-file already exists then the output file can become malformed.
```
pgp.GenerateKey("public.txt", "private.txt", "username", "password", 1024);
pgp.GenerateKey("public.txt", "private.txt", "username", "password", 512);
```

This example generates a long key, then a shorter key to the same file. The resulting file:

> -----BEGIN PGP PUBLIC KEY BLOCK-----
> Version: BCPG C# v1.8.5.0
> 
> mEsEXc185AECAKdAfTMUCLXi2vRsz0RwOx2OMJuDUAS69kMyYxAYpZkorM/wqoTs
> DkL3/X3Eqm0NNqN6BU9EUPzOFord9Le/uTMABRO0CHVzZXJuYW1liFwEEAECAAYF
> Al3NwzQACgkQBD+fFOKPU+jIXAH9GyYQCEExNSBoBt4D0yiNi4fb1hjppp0CwfNI
> EpHQ5cGgAKzcJ1ks1qlvOzLJfwBkDknGN1uxsRJ7G154vhFnJA==
> =gfJE
> -----END PGP PUBLIC KEY BLOCK-----
> N7Uml6jYu4LJ3id/USTkFBuUOLwnndcsA
> /vUtA9PiYg4uFIICGRBvW9EzS/QDgUK8FfJofDXNs2xBMUBiZJV2HBjnLZByC4X3
> 8BXwbc/NcnhR83ND9xAAw4f/YrpL
> =vu/P
> -----END PGP PUBLIC KEY BLOCK-----

I would expect that writing the key to the file would use [File.WriteAllText()](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealltext?redirectedfrom=MSDN&view=netframework-4.8#System_IO_File_WriteAllText_System_String_System_String_) or something similar which overwrites the whole file.

I found where I would make an adjustment:
https://github.com/mattosaurus/PgpCore/blob/31479efd143e4aa11b446851b33b5d36051b5d0a/PgpCore/PGP.cs#L1112-L1113

**Comment by mattosaurus** [comment]
Thanks for submitting the PR request, I've merged these changes and uploaded v2.1.1 to NuGet.
