### ISSUE TITLE
A way to get the public key fingerprint

### ISSUE THREAD

**Issue by blackboxlogic** [mattosaurus/PgpCore#47]
Feature request:
A way to get a public key's fingerprint from a public-key stream or file.

**Comment by blackboxlogic** [comment]
Something like:

```
public byte[] GetFingerprint(Stream publicKeyStream)
		{
			var publicKey = Utilities.ReadPublicKey(publicKeyStream);
			return publicKey.GetFingerprint();
		}
```

**Comment by blackboxlogic** [comment]
I've leave this issue open for your consideration (if you want to add the functionality) but It looks like all I needed is:
```c#
Utilities.ReadPublicKey("public").GetFingerprint();
```

**Comment by mattosaurus** [comment]
Ah, I forgot about that, think I'll just leave it in utilities then rather than adding a new method to the PGP object.
