### ISSUE TITLE
Org.BouncyCastle.Bcpg.OpenPgp.PgpException: 'Checksum mismatch at 0 of 2'

### ISSUE THREAD

**Issue by KolathDragon** [mattosaurus/PgpCore#53]
Used the following code fragment to perform a test of PgpCore. It fails with, "Org.BouncyCastle.Bcpg.OpenPgp.PgpException: 'Checksum mismatch at 0 of 2'" when attempting to decrypt the file. 

                // Generate keys
                pgp.GenerateKey(@"C:\TEMP\keys\public.asc", @"C:\TEMP\keys\private.asc", "email@email.com", "passwo0d");
                // Encrypt file
                pgp.EncryptFile(@"sample.pdf", @"sample_pdf_encrypted.pgp", @"C:\TEMP\keys\public.asc", true, true);
                // Decrypt file
                pgp.DecryptFile(@"sample_pdf_encrypted.pgp", @"sample_pdf_UNencrypted.pgp", @"C:\TEMP\keys\private.asc", "passw0rd");

**Comment by mattosaurus** [comment]
Your password is incorrect, you're encrypting with "passwo0d" but decrypting with "passw0rd".

**Comment by KolathDragon** [comment]
Hey man, thanks alot. Sorry it was a so simple.



--=== Kolath Dragon ===--

________________________________

**Comment by mattosaurus** [comment]
No worries, just glad it wasn't something wrong with the package :)

**Comment by umutgur** [comment]
What if this happens in Encryption? By the way I try to encrypt a memory stream, there will no file. Can this affect that? Also I am creating key with just publicKey and privateKey like this 

```
public async Task<byte[]> Encrypt(byte[] streamToEncrypt, string publicKey, string privateKey, string passPhrase)
        {
            Stream inputStream = new MemoryStream(streamToEncrypt);
            Stream outputStream = new MemoryStream();
            byte[] result;

            using (PGP pgp = new PGP())
            {
                pgp.GenerateKey(publicKey, privateKey);

                using (Stream privateKeyStream = new FileStream(privateKey, FileMode.Open))
                using (Stream publicKeyStream = new FileStream(publicKey, FileMode.Open))
                {
                    pgp.EncryptStreamAndSign(inputStream, outputStream, publicKeyStream, privateKeyStream, passPhrase);
                }
            }

            using (MemoryStream streamReader = new MemoryStream())
            {
                outputStream.CopyTo(streamReader);
                result = streamReader.ToArray();
            }

            return result;
        }
```

**Comment by mattosaurus** [comment]
Are you getting the same error of "Checksum mismatch at 0 of 2" as in the original issue?

**Comment by umutgur** [comment]
@mattosaurus that's my fault, I did not check what that do `pgp.GenerateKey()` my private key changed that's why this error. 

Thanks for this great package.
