### ISSUE TITLE
Base64 encode encrypted stream

### ISSUE THREAD

**Issue by lwalker-kforce** [mattosaurus/PgpCore#55]
I have a method that encrypts a `Stream`:
`public async Task<Stream> EncryptAsync(Stream streamToEncrypt, string publicKey)
        {
            using var pgp = new PGP();
            Stream outputStream = new MemoryStream();
            using (streamToEncrypt)
            using (var publicKeyStream = publicKey.ConvertToStream())
            {
                await pgp.EncryptStreamAsync(streamToEncrypt, outputStream, publicKeyStream, true, true);
                outputStream.Seek(0, SeekOrigin.Begin);
                return outputStream;
            }
        }`

It is being used by a web endpoint so encoding the encrypted data is likely the best way to reduce formatting issues etc. (e.g. Base64). What is a good way to encode the encrypted `Stream` without hitting the constraints of multiple `Byte[]` copies and `MemoryStream` size constraints?

**Comment by cravecode** [comment]
@lwalker-kforce IMO that is out of the scope of this library. 
Are you concerned about large files? If so, returning the results as a base64 encoded string may not be the best approach. If it were me, I'd consider writing the stream to the response buffer and setting the Content-Type header to something like `application/octet-stream`. This way the response can be handled like downloading a large file.

**Comment by lwalker-kforce** [comment]
@cravecode The response stream is not really a concern. As you indicated, it can be returned with the appropriate content type. The size of the inbound Stream on the request was what I was referring to.

**Comment by mattosaurus** [comment]
Hi @lwalker-kforce, can you read from the inbound stream directly, something like the (untested) function below maybe?

```
public static class PGPEncrypt
{
	[FunctionName("PGPEncrypt")]
	public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req, ILogger log)
	{
		log.LogInformation("C# HTTP trigger function processed a request.");

		PGP pgp = new PGP();

		using (MemoryStream outputStream = new MemoryStream())
		{
			using (Stream publicKeyStream = new FileStream("/Data/Public", FileMode.Open, FileAccess.Read))
				await pgp.EncryptStreamAsync(req.Body, outputStream, publicKeyStream);
				return new FileStreamResult(outputStream, "application/octet-stream");
		}
	}
}
```
