### ISSUE TITLE
If the encrypted input is malformed, throw a null reference error that is hard to diagnose

### ISSUE THREAD

**Issue by cravecode** [mattosaurus/PgpCore#57]
If the contents of the encrypted stream isn't a valid encrypted value format, the decrypt function throws a unhelpful null reference error.

Example scenario: attempting to decrypt a file that is already decrypted.

**Comment by cravecode** [comment]
PR to come shortly

**Comment by mattosaurus** [comment]
Closed as fixed in your PR
