### ISSUE TITLE
Refactor to Use Interface

### ISSUE THREAD

**Issue by mattosaurus** [mattosaurus/PgpCore#64]
Create IPGP interface object

**Comment by bitcoinbrisbane** [comment]
Might be worth having breaking them down to something like

- IPGPEncrypt
- IPGPSign

Then

```
IPGP : IPGPEncrypt, IPGPSign
```

**Comment by mattosaurus** [comment]
Good idea, the current PGP class is getting a bit unwieldy so makes sense to split it out to make it easier to maintain.

**Comment by bitcoinbrisbane** [comment]
Cool.  Ive started on my fork. I'm on a few projects ATM that I'm using a bit of PGP, so happy to add some time to your lib.

**Comment by bitcoinbrisbane** [comment]
Started this : https://github.com/bitcoinbrisbane/PgpCore/commit/f06c24fcf533283ddc91e2653493396daf821f7c

**Comment by mattosaurus** [comment]
Awesome, thanks for making a start on this.

**Comment by bitcoinbrisbane** [comment]
> Awesome, thanks for making a start on this.

Should get this done this week.
