### ISSUE TITLE
Allow Keys to be Held in Memory

### ISSUE THREAD

**Issue by mattosaurus** [mattosaurus/PgpCore#65]
Add an internal keystore to PGP allowing keys to be stored on initialisation.

How to choose desired keys if multiples allowed?

**Comment by martinjt** [comment]
My thoughts on this...

I'm currently working on a Web API that has some keys supplied, and then encrypts and signs some XML before sending it on.

I'm storing the keys in a central config store (Azure KeyVault in this case), so I want to be able to load them at startup, and use them for the lifetime of the app.

What I'm thinking is, the EncryptionKeys calls... if that implemented `IEncryptionKeys`, we could supply a different implementation to the methods under the hood.  Then, provide an overload of on the methods to provide a IEncryptionKeys implementation, or the streams etc.  That way, we can have an implementation that returns In Memory ones.

If you agree, I can have a go at a PR for it.

**Comment by bitcoinbrisbane** [comment]
Could we use secure string too?

**Comment by mattosaurus** [comment]
So I haven't used SecureString before but it seems that they're activly advising against using it (gives a false sense of security maybe).

https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netcore-3.1
https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md

If the password is being passed in via a string then it's going to be just as (in)secure as using a string all the way down, though within PgpCore it would be slightly more secure.

I'm not completly adverse to this but from the documentation it doesn't seem like it would be a good idea. Is this something you regually use and could advise on?

**Comment by cainy-a** [comment]
Pull #109 which uses strings to store keys

**Comment by mattosaurus** [comment]
Added in v5.1.0
