### ISSUE TITLE
Issue with decrypting binary files

### ISSUE THREAD

**Issue by kamesh95** [mattosaurus/PgpCore#68]
Decryption fails with error when I try to decrypt a file that has binary contents instead of the normal -----BEGIN PGP MESSAGE----- text file. I have checked the private key and public key are correct, also tried to decrypt it with openpgp js module with binary option and it worked there. But doesn't work with PgpCore, kindly help me out, I am using this in Azure function. See code below. Thanks. 

```
        public virtual async Task Decrypt(Client client, Stream blobStream, CloudBlobStream decryptedStream, ILogger log)
        {
            try
            {
                using (PGP pgp = new PGP())
                {
                    Stream privateKeyStream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(client.PgpConfig.PrivateKey));
                    log.LogInformation($"::::::x {pgp.FileType.ToString()}"); // this prints binary for all files
                    await DecryptStreamAsync(pgp, blobStream, decryptedStream, privateKeyStream, client.PgpConfig.Passphrase);
                    await decryptedStream.CommitAsync();
                }
            } 
            catch (Exception ex)
            {
                log.LogError($"Error while decrypting file {ex.Message} {ex.StackTrace}");
                exception = ex;
            }
        }
       
         public virtual async Task DecryptStreamAsync(PGP pgp, Stream stream, CloudBlobStream decryptedStream, Stream privateKeyStream, string passphrase)
        {
            await pgp.DecryptStreamAsync(stream, decryptedStream, privateKeyStream, passphrase);
        }
```

`Error while decrypting file unknown object in stream Reserved    at Org.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.NextPgpObject() in D:\a\1\s\crypto\src\openpgp\PgpObjectFactory.cs:line 119
   at Org.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.AllPgpObjects() in D:\a\1\s\crypto\src\openpgp\PgpObjectFactory.cs:line 136
   at PgpCore.PGP.DecryptAsync(Stream inputStream, Stream outputStream, Stream privateKeyStream, String passPhrase)
   at PgpCore.PGP.DecryptStreamAsync(Stream inputStream, Stream outputStream, Stream privateKeyStream, String passPhrase)
   at SofyImportV3.common.PgpDecrypter.DecryptStreamAsync(PGP pgp, Stream stream, CloudBlobStream decryptedStream, Stream privateKeyStream, String passphrase) in /Users/kamesh/Desktop/Sofy/SofyUnit/azure_functions/SofyImportV3/common/PGPDecrypter.cs:line 166
   at SofyImportV3.common.PgpDecrypter.Decrypt(Client client, Stream blobStream, CloudBlobStream decryptedStream, ILogger log) in /Users/kamesh/Desktop/Sofy/SofyUnit/azure_functions/SofyImportV3/common/PGPDecrypter.cs:line 131`

**Comment by mattosaurus** [comment]
Hi, decryption of binary files works for me.

```
            // Arrange
            Arrange(keyType);
            PGP pgp = new PGP();

            // Act
            pgp.EncryptFileAndSign(contentFilePath, encryptedContentFilePath, publicKeyFilePath1, privateKeyFilePath1, password1, armor: false);
            pgp.DecryptFile(encryptedContentFilePath, decryptedContentFilePath1, privateKeyFilePath1, password1);
            string decryptedContent = File.ReadAllText(decryptedContentFilePath1);

            // Assert
            Assert.True(File.Exists(encryptedContentFilePath));
            Assert.True(File.Exists(decryptedContentFilePath1));
            Assert.Equal(content, decryptedContent.Trim());

            // Teardown
            Teardown();
```

Does it work for your file if you try and decrypt it like the above? If not are you able share a solution with dummy data/keys that I can take a look at?
