### ISSUE TITLE
ClearSignStream fails if any line in the stream has trailing whitespaces

### ISSUE THREAD

**Issue by Quit** [mattosaurus/PgpCore#69]
After hours of debugging, I've tracked down an inconsistency in this library compared to gpg (on Windows at least):

Any text that contains a line which ends in spaces (i.e. " \n", " \r\n" or similar) will produce a file which can be verified with PgpCore (i.e. `VerifyClearStream`), but will fail validation with gpg (bad signature).

Example:

```csharp
var text = "Test \nString";
using var inputStream = new MemoryStream(Encoding.ASCII.GetBytes(text));
using var outputStream = new MemoryStream();
using var keyStream = File.OpenRead("key.pgp");
var keyPassword = "<boing>";

var pgp = new PGP()
{
    CompressionAlgorithm = Org.BouncyCastle.Bcpg.CompressionAlgorithmTag.Uncompressed,
    FileType = PGPFileType.Binary,
    HashAlgorithmTag = Org.BouncyCastle.Bcpg.HashAlgorithmTag.Sha512,
    PublicKeyAlgorithm = Org.BouncyCastle.Bcpg.PublicKeyAlgorithmTag.RsaSign,
    PgpSignatureType = 0
};

pgp.ClearSignStream(inputStream, outputStream, keyStream, keyPassword);

File.WriteAllBytes("borked.txt.asc", outputStream.ToArray());

var gpg = Process.Start("gpg", "--verify borked.txt.asc");
gpg.WaitForExit();
Console.WriteLine(gpg.ExitCode);
```

This will return 1 for any  `text` which has a line with trailing whitespaces, and 0 for those without. As far as I can tell, there have been some arguments in the PGP/GPG community in the past about how this should be handled (with `Binary` as proposed solution to avoid this issue altogether), but none of the options in PgpCore seem to be able to create a clear signed file which can be verified by gpg.

**Comment by mattosaurus** [comment]
Hi, I newline characters are excluded from the signature generation but I didn't realise trailing whitespace was also an issue. I'll see if I can update the signature generator to account for these as well.
