### ISSUE TITLE
Add method to extract clear signed content

### ISSUE THREAD

**Issue by mattosaurus** [mattosaurus/PgpCore#77]
> Hi @tkaradimitris, DecryptFileAndVerify is intended for decrypting and verifying encrypted and signed files which is why it requires both a public and private key. There's currently no functionality for extracting the clear signed content as I'd figured these message would mostly be being read by humans.
> 
> If this is something that you need then feel free to submit a PR if you're able, or if not I'll add it to my work list and get to it when I have a chance.

Thank you @mattosaurus for the answer and the great work. I am not sure what I need to use from BouncyCastle to extract content from signed files / streams, but if I manage to find examples from other solutions I will try to submit a PR.

_Originally posted by @tkaradimitris in https://github.com/mattosaurus/PgpCore/issues/40#issuecomment-647317164_

**Comment by RodneyRichardson** [comment]
I've added versions of VerifyClearArmoredString+Async (called VerifyAndRead...) to accomplish this. There are probably more functions that could benefit from this, but these are the methods I needed. 

I've updated the based method VerifyClear+Async, so it should be straightforward to add it for other function as required.
