### ISSUE TITLE
Using PGPCore in AzureFunctions with EncryptStream

### ISSUE THREAD

**Issue by Drwal06** [mattosaurus/PgpCore#8]
I've tried utilizing this library within Azure functions and having issues with the encryption methods for Streams.
When I EncryptStream, the output does not seem to be formatted correctly because i am unable to decrypt, getting an exception because PgpObjectFactory.NextPgpObject is null.
If I utilize EncryptFile and DecryptFile everything works.
Even if I EncryptFile and then convert that to a stream and DecryptStream, it works.
I'm going to use this in Azure Functions integrated with Azure storage for the files and Azure KeyVault for my pgp keys/passphrase/etc so the stream methods are what I want to get working.
Any idea what my issue is?

**Comment by mattosaurus** [comment]
Hi @Drwal06, I've been doing something similar recently and my first guess would be that you need to reset the stream to the beginning before decrypting.

`myStream.Seek(0, SeekOrigin.Begin);`

If that's not the case then let me know and I'll have a look into it in more detail when I get a chance.

**Comment by Drwal06** [comment]
I've tried that suggestion and that does not solve it.  In utilizing a different library, what i can tell is that the EncryptStream method here creates a much smaller pgp file.  I don't think there is anything wrong with the DecryptStream method, as i haven't had issues decrypting streams using this function on files encrypted outside this library.
There seems to be something odd with the Encryption side of the equation that causes the file to be incorrectly formatted.

I've gone with a paid solution now due to time constraints that i was able to plug in and have work right away.  I would've much rather went with this library or other open source solutions, though!

**Comment by mattosaurus** [comment]
Do you have any code you can share demonstrating this?

The EncryptSteam and DecryptSteam methods work as expected in the test project [here](https://github.com/mattosaurus/PgpCore/blob/master/PgpCoreTest/Program.cs), though it's possible that it's fine with file streams but not other streams for whatever reason. Will see if I can knock up an Azure function to test this.

**Comment by mattosaurus** [comment]
I've added an example of encrypting and decrypting memory streams to the test project.

https://github.com/mattosaurus/PgpCore/blob/master/PgpCoreTest/Program.cs

Feel free to reopen this issue if it doesn't work for you and you can send me your test code.
