### ISSUE TITLE
Add extension methods for input/output strings

### ISSUE THREAD

**Issue by mattosaurus** [mattosaurus/PgpCore#82]
Add an extension methods class to cast strings to streams and streams to strings to work with the current stream methods as in #81

**Comment by ZippoLag** [comment]
It'd also be nice if the secret key we're using could come from a string rather than a stream. My use case is that I have my private key in an azure key vault, so when I get it I just get a string content which I need to wrap around this to be able to use with pgpcore:

        public static MemoryStream GenerateStreamFromString(string s)
        {
            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            writer.Write(s);
            writer.Flush();
            stream.Position = 0;
            return stream;
        }

**Comment by mattosaurus** [comment]
Added in v5.1.0
