### ISSUE TITLE
Sending to protonmail

### ISSUE THREAD

**Issue by bitcoinbrisbane** [mattosaurus/PgpCore#83]
Hi @mattosaurus,

Trying to send to protonmail and pulling the pub key from their server.  After the below code, Protonmail says it can't decrypt.  Any thoughts?

```csharp
String email = "test@protonmail.com";
String body = message.Value.ToString();

                if (email.ToLower().EndsWith("@protonmail.com"))
                {
                    String keyserverUrl = String.Format("https://api.protonmail.ch/pks/lookup?op=get&search={0}", email);

                    using (HttpClient client = new HttpClient())
                    {        
                        using (HttpResponseMessage keyserverResponse = await client.GetAsync(keyserverUrl))
                        using (Stream publicKeyStream = await keyserverResponse.Content.ReadAsStreamAsync())
                        {
                            PGP pgp = new PGP();
                            byte[] byteArray = Encoding.ASCII.GetBytes(this.ToString());
                            using (Stream inputStream = new MemoryStream(byteArray))
                            {
                                using (Stream outputStream = new MemoryStream())
                                {
                                    using (StreamReader streamReader = new StreamReader(outputStream))
                                    {
                                        using (Stream privateKeyStream = new FileStream("private.asc", FileMode.Open))
                                        {
                                            await pgp.EncryptStreamAndSignAsync(inputStream, outputStream, publicKeyStream, privateKeyStream, "", true);

                                            outputStream.Seek(0, SeekOrigin.Begin);
                                            body = streamReader.ReadToEnd();
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

```

**Comment by bitcoinbrisbane** [comment]
Hmm, strange.  Seems to work ok to Protonmail and read on the mobile app, just not the web page.

**Comment by mattosaurus** [comment]
Do you mean it works on their mobile app but not on their webpage and you're sending the message using the above code to both or that you're sending a message from a webpage and a mobile app and one is being sent and the other isn't?

If it's the later then it may be something with the webpage cutting off the stream before it's finished being output. If the former then it sounds like a Protonmail issue, though certainly a weird one.

It might be worth trying to capture the body of the API call you're making using Fiddler or similar to see if it can then be decrypted with PGPCore or if it's getting obviously truncated by one method.

**Comment by bitcoinbrisbane** [comment]
> Do you mean it works on their mobile app but not on their webpage and you're sending the message using the above code to both or that you're sending a message from a webpage and a mobile app and one is being sent and the other isn't?
> 
> If it's the later then it may be something with the webpage cutting off the stream before it's finished being output. If the former then it sounds like a Protonmail issue, though certainly a weird one.
> 
> It might be worth trying to capture the body of the API call you're making using Fiddler or similar to see if it can then be decrypted with PGPCore or if it's getting obviously truncated by one method.

To be clear, if I send an encrypted mail to my proton account using the above, when I view the email on their mobile app it decrypts fine.

If I view it via a browser (same account etc), proton mail says it can't decrypt.  Ill ping them for help.
