### ISSUE TITLE
Signature verification using a subkey

### ISSUE THREAD

**Issue by mjwood7** [mattosaurus/PgpCore#88]
It looks like the signature validation routine fails when verifying a message signed using a non-primary subkey. Counter parties may create separate sub keys for signature and encryption to separate concerns. If I create such a key, I can get decryption to work, but not signature validation. I think that's why the bouncyCastle validation routine is more complex -- it does the validation after reading through pgpLiteralData, etc. 

https://github.com/bcgit/bc-csharp/blob/master/crypto/test/src/openpgp/examples/SignedFileProcessor.cs

**Comment by mattosaurus** [comment]
Thanks for pointing this out, I don't use subkeys so hadn't spotted this previously. I'll have a look at getting this working when I get a chance, or if you need it sooner feel free to submit a PR.

**Comment by mattosaurus** [comment]
Are you able to provide me with a test solution (including keys) that replicates this and then I'll take a look into it.

**Comment by mattosaurus** [comment]
Yep, this was an issue with picking the wrong keys for signing.
