### ISSUE TITLE
EncryptStream using MemoryStream output (no file output)

### ISSUE THREAD

**Issue by ShakatarYT** [mattosaurus/PgpCore#9]
Hello,

I'm starting C# development so i'm very bad.

This is my code :

```
            PGP pgp = new PGP();

            Stream inputFileStream = new MemoryStream(System.Text.Encoding.UTF8.GetBytes("test_basic_messsage"));
            Stream outputFileStream = new MemoryStream();
            Stream publicKeyStream = new FileStream(Utils.app_directory + @"keys\public.asc", FileMode.Open);

            pgp.EncryptStream(inputFileStream, outputFileStream, publicKeyStream);

            StreamReader reader = new StreamReader(outputFileStream);
            string text = reader.ReadToEnd();

            MessageBox.Show(outputFileStream.Length.ToString()); //Messagebox to see outputFileStream length (it display 890)
            MessageBox.Show(text); //Messagebox to see pgp Message (it display nothing)
            MessageBox.Show(text.Length.ToString()); //Messagebox to see pgp message length (it display 0)
```

I'm trying to store a pgp message in a string variable but i cannot, with this code, `outputFileStream.Length` equals to 890 but `reader.ReadToEnd()` equals to nothing.

But when i replace `Stream outputFileStream = new MemoryStream();` by `Stream outputFileStream = File.Create(Utils.app_directory + @"keys\content.pgp")` it's working because i see the pgp message in the content.pgp file...

Sorry for my bad english, i'm french...

**Comment by mattosaurus** [comment]
Hi @ShakatarYT, this is because the outputFileStream is at the end of the stream, if you reset it to the start then you can read it correctly.

`
outputFileStream.Seek(0, SeekOrigin.Begin);
StreamReader reader = new StreamReader(outputFileStream);
`

Your English is certainly much better than my French :)

**Comment by mattosaurus** [comment]
I've updated the test project to add an example of encrypting and decrypting memory streams.

https://github.com/mattosaurus/PgpCore/blob/master/PgpCoreTest/Program.cs

**Comment by ShakatarYT** [comment]
Thanks :wink:
