### ISSUE TITLE
Decrypt pgp without password

### ISSUE THREAD

**Issue by AnnieNJ** [mattosaurus/PgpCore#92]
Can we decrypt with private.asc only without password? My business partner gives me the private.asc only.
Thank you!

**Comment by AnnieNJ** [comment]
Never Mind my st***d question. I can answer it myself. By the way, Thank you very much, your package lift 99.99% of the work. It's a little tricky to install though. Well ppl needs to do a little work before sitting back and enjoy!

**Comment by mattosaurus** [comment]
No worries, happy to hear you're finding the library useful :)
