### ISSUE TITLE
Compatibility issues with the package 

### ISSUE THREAD

**Issue by prayank23** [mattosaurus/PgpCore#93]
Is there a way to fix this error or I will have to try some other Nuget package for Android app in Visual Studio 2017?

Error:
<pre><code>Package PgpCore 2.4.2 is not compatible with monoandroid90 (MonoAndroid,Version=v9.0). Package PgpCore 2.4.2 supports: netstandard2.1 (.NETStandard,Version=v2.1)</pre></code>

**Comment by mattosaurus** [comment]
I'm planning to add support for .net core 2.2 and 3.1 in the next release #84 but not .net core 2.1. netstandard 2.1 is currently supported and works with mono android V10 so I suggest updating that if possible.

**Comment by prayank23** [comment]
Thanks. I will try. First I will have to update VS to 2019 which supports mono android V10.

**Comment by prayank23** [comment]
![image](https://user-images.githubusercontent.com/13405205/92315653-639e2500-f006-11ea-8b2a-8459cf5ef499.png)

Its working in VS 2019 after changing target framework to Android 10 👍
