### ISSUE TITLE
DecryptStreamAsync on Azure Block Blobs returning empty stream

### ISSUE THREAD

**Issue by mizrael** [mattosaurus/PgpCore#94]
I am writing an Azure Function to decrypt a previously encrypted file stored in an Azure Blob. Ideally, I would like to use the `OpenWrite/Read` methods on BlobBlockClient in order to avoid downloading and encrypting in memory. I was hoping to use something like this:

```
await using var sourceStream = await sourceBlobClient.OpenReadAsync();

var destBlobClient = destContainer.GetBlockBlobClient(command.SourcePath);
await using var destStream = await destBlobClient.OpenWriteAsync(true);

await using var privateKey = _pgpKeysProvider.GetPrivate();
using var pgp = new PgpCore.PGP();

await pgp.DecryptStreamAsync(sourceStream, destStream, privateKey.Key, privateKey.Passphrase);
```

I am however experiencing few issues:
1) `OpenReadAsync()` returns a non-seekable stream, which apparently cannot be used by `DecryptStreamAsync()`. To mitigate this, I'm downloading the blob in memory, which I honestly wanted to avoid:
    ```
    await using var sourceStream = new MemoryStream();
    await sourceBlobClient.DownloadToAsync(sourceStream);
    sourceStream.Position = 0;
    ```
    Is there any way to fix this?
2) even if I bite the bullet and download the encrypted file into a `MemoryStream`, `DecryptStreamAsync()` is returning an empty stream. The only solution I have found so far is to decrypt to another `MemoryStream `and then upload this one to the Blob Container. Which I also wanted to avoid. I even tried to get rid of the `using` and manually call Dispose() on the streams, just in case there was any potential issue there. No luck.

Small files aren't a problem, I'm concerned about big ones (eg. 4gb or more)

Any advice?

**Comment by mattosaurus** [comment]
Hi, the issue is caused by a method in the underlying BouncyCastle crypto library.

https://github.com/bcgit/bc-csharp/blob/5bd4c8c70f80f1e7ead8e3c73459b78eb93d0ef7/crypto/src/openpgp/PgpUtilities.cs#L414-L429

Interestingly there's a comment indicating that the restriction isn't needed so it might be worth raising an issue there to see if it's still necessary or not, though currently the way the GetDecoderStream method functions means that the stream does need to be seekable.

Feel free to submit a PR if you'd like to rewrite this method (there's a replica in PgpUtilities though it's not referenced at the moment), if not I'll have a look at this when I get a chance.

**Comment by mizrael** [comment]
hi @mattosaurus thanks for the quick reply! I'll create an issue on BouncyCastle for now and in the meantime, I'll try to update the code myself.
Thanks!

**Comment by mahdighazali1985** [comment]
Hi @mizrael,
I'm working on the same cas as you! Building an Azure Function to Encrypt and Decrypt an Audio File stored in Azure Storage.
I wrote this code, but it always fails at this level «await pgp.EncryptStreamAsync(sourceStream, outputStream);». The error is «inputStream must be seek-able»:
Thank you for your help! (will pay you a coffee in Montreal :) )
` static async Task Main()
        {
            
            string connectionString = Environment.GetEnvironmentVariable("AZURE_STORAGE_CONNECTION_STRING");
            ////Create a unique name for the container
            string containerName = "audioinput";
            string filename = "abc.wav";

            //// Create a BlobServiceClient object which will be used to create a container client
            BlobServiceClient blobServiceClient = new BlobS                //EncryptionKeys encryptionKeys;
                //using (Stream publicKeyStream = new FileStream(@"C:\Users\mahdi.ghazali\OneDrive - Accenture\Documents\Projects\Desjardins\NLP\pgpkeys\public.asc", FileMode.Open))
                //    encryptionKeys = new EncryptionKeys(publicKeyStream);
erviceClient(connectionString);
            BlobContainerClient sourcecontainer = blobServiceClient.GetBlobContainerClient(containerName);
            BlobClient blobClient = sourcecontainer.GetBlobClient(filename);

            if (sourcecontainer.Exists())
            {

                var sourceStream = new MemoryStream();
                
					//Download blob to MemoryStream
                    await blobClient.DownloadToAsync(sourceStream);
                    sourceStream.Position = 0;
					
					//OutputStream
                    await using var outputStream = new MemoryStream();
					
					//Get encryptionkeys
                    EncryptionKeys encryptionKeys;
                    using (Stream publicKeyStream = new FileStream(@"...\public.asc", FileMode.Open))
                        encryptionKeys = new EncryptionKeys(publicKeyStream);

                    PGP pgp = new PGP(encryptionKeys);

                await pgp.EncryptStreamAsync(sourceStream, outputStream);
                

            }
            else
            {
                Console.WriteLine("container doesn't exist");
            }

        }`

**Comment by mattosaurus** [comment]
I'm not sure if it's been updated but I don't have any issues reading/writing to Azure blob storage through a function now.

I've created an example function here to demonstrate this.

https://github.com/mattosaurus/PgpEncrypt
