### ISSUE TITLE
Message is not a simple encrypted file

### ISSUE THREAD

**Issue by dennisholmer** [mattosaurus/PgpCore#96]
I received a PGP encrypted file from a bank, and for some reason when decrypting it I got message "Message is not a simple encrypted file".

I went throught the source code and realized that there is a `PgpObject` not caught in `PGP.DecryptAsync`, namely `PgpSignatureList`. I simply added it like so and presto, it works!

![image](https://user-images.githubusercontent.com/1439413/94583514-0f850a00-026d-11eb-9a17-2fa2c27928b5.png)

**Comment by mattosaurus** [comment]
Thanks for pointing that out, I'll add this in to the next release of the package.
