### ISSUE TITLE
Install Problem 

### ISSUE THREAD

**Issue by warpdriv** [mattosaurus/PgpCore#98]
Hi,

I'm using VS 2019 working on a .Net Framework console app. When I try to install it gives me this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'PgpCore 2.4.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I have also tried 4.7.1 and 4.6.1. Can I please get some help on what version is to be used in my project?

Thank you for your help.

**Comment by mattosaurus** [comment]
Hi,

Currently PgpCore only works with .NET Core and not .NET Framework. I'm in the process of making some other changes as part of a v3 release, one of which is to target .NET Standard 2.0 which should allow for backward compatability with .NET Framework v4.7.2 and later #95 

Hopefully I'll have v3 published to NuGet in the next few days but if you need it to work now I'd upgrade to .NET Core if possible.

**Comment by warpdriv** [comment]
Thank you for the quick response. I'm too entrenched to upgrade. I'll keep an eye out for release.

Also, Thank You for making our world and eaiser place to code. :)
